package com.example.repository.chemistry

import com.example.repository.Objective
import com.example.repository.Questions

class Chemistry2012Repo {

    val chemistry2012 = listOf<Questions>(

        Questions( objective = Objective( "1", "", "", "",
            "The number of orbitals in a p-sub level of an atom is",
            "A. 2",
            "B. 3",
            "C. 5",
            "D. 6",
            "B. 3", "B")
        ),

        Questions( objective = Objective( "2", "", "", "",
            "Which of the following electron configurations represents that of an atom in its ground state?",
            "A. 1s 2 2s1 2p1",
            "B. 1s2 2s2 2p6 3s1 3p1",
            "C. 1s2 2s1 2p3",
            "D. 1s 2s2 2p6 3s0",
            "D. 1s 2s2 2p6 3s0", "D")),

        Questions( objective = Objective( "3", "", "", "3",
            "A beam of particles was passed between charged as illustrates in the diagram below." +
                    "Z, Y and Z are respectively",
            "A. electron, neutron and proton",
            "B. electron, proton and neutron",
            "C. proton, neutron and electron",
            "D. proton, electron and neutron.",
            "C. proton, neutron and electron", "C")),

        Questions( objective = Objective( "4", "", "", "",
            "Which of the following ions has an electron configuration different from the other?",
            "A. 17CI-",
            "B. 8O2-",
            "C. 12Mg2+",
            "D. 13AI3+",
            "A. 17CI-", "A")),

        Questions( objective = Objective( "5", "", "", "",
            "The atomic radii of metals are usually",
            "A. greater than their ionic radii",
            "B. equal to their ionic radii",
            "C. less than their ionic radii",
            "D. less than those of non-metals in the same period",
            "A. greater than their ionic radii", "A")),

        Questions( objective = Objective( "6", "", "", "",
            "Two elements, X and Y are in the same group on the periodic table because they both have the same",
            "A. number of electronic shells",
            "B. number of valence electrons",
            "C. atomic size",
            "D. atomic number",
            "B. number of valence electrons", "B")),

        Questions( objective = Objective( "7", "", "", "",
            "The d-block elements are paramagnetic because they",
            "A. contain paired electrons which are repelled by magnetic field",
            "B. contain unpaired electrons in the partially filled 3d-orbital",
            "C. contain paired electrons which are repelled by magnetic field force",
            "D. have delocalized valence electrons",
            "B. contain unpaired electrons in the partially filled 3d-orbital", "B")),

        Questions( objective = Objective( "8", "", "", "",
            "Which of the following statements about a radioactive substance is/are correct? l. lt emits radiation continuously and spontaneously. ll. The emitted radiations are affected by temperature and pressure III. The radiation can penetrate opaque matter",
            "A. ll only",
            "B. l and ll only",
            "C. l and lll only",
            "D. ll and lll only",
            "C. l and lll only", "C")),

        Questions( objective = Objective( "9", "", "", "",
            "Which of the following elements is a metalloid?",
            "A. Carbon",
            "B. Oxygen",
            "C. Silicon",
            "D. Sodium",
            "C. Silicon", "C"), ),

        Questions( objective = Objective( "10", "", "", "",
            "Which of the following halogens is liquid at room temperature?",
            "A. Chlorine",
            "B. Fluorine",
            "C. iodine",
            "D. Bromine",
            "D. Bromine", "D")),


        Questions( objective = Objective( "11", "", "", "",
            "The shape of a graphite crystal is",
            "A. tetrahedral",
            "B. pyramidal",
            "C. hexagona",
            "D. octahedral",
            "C. hexagonal", "C")),

        Questions( objective = Objective( "12", "", "", "",
            "The complex compound formed by the combination of two elements with a large electronegativity difference is likely to be",
            "A. polar covalent",
            "B. giant molecular",
            "C. covalent",
            "D. ionic",
            "D. ionic", "D")),

        Questions( objective = Objective( "13", "", "", "13",
            "The complex compound formed when aluminum dissolves in aqueous sodium hydroxide is",
            "A. Na3Al(OH)4.",
            "B. NaAl(OH)4",
            "C. NaAl(OH)3",
            "D. Na2Al(OH)3",
            "B. NaAl(OH)4", "B")),


        Questions( objective = Objective( "14", "", "", "",
            "The vapour pressure of a liquid depends on l. temperature. ll. rate of condensation. III. cohesive forces holding the particles together",
            "A. l only",
            "B. l and ll only",
            "C. l and lll only",
            "D. ll and lll only",
            "C. l and lll only", "C")),

        Questions( objective = Objective( "15", "", "", "",
            "MgO does not readily dissolve in water because",
            "A. of its high melting point",
            "B. it is a covalent compound",
            "C. it forms a hydroxide when dissolved in water",
            "D. its lattice energy is higher than its hydration energy",
            "D. its lattice energy is higher than its hydration energy", "D")),


        Questions( objective = Objective( "16", "", "", "16",
            "Consider the following reaction equation: CaCO3(s) + 2HCI(aq) → CaCl2(aq) + H2O(l) + CO2(g). What mass of CaCI2 would be obtained when 25.0g of CaCO3(s) is reacted with excess HCI(aq)? [CaCO3=100;CaCI(2 = 111]",
            "A. 4.00g",
            "B. 4.44 g",
            "C. 18.9 g",
            "D. 27.8 g",
            "D. 27.8 g", "D")),

        Questions( objective = Objective( "17", "", "", "17",
            "The number of sulphur atoms in 3.20g of SO2(g) is [O = 16.0;S = 32.0; Avogadro constant = 6.02 x 1023]",
            "A. 3.01 x 1022",
            "B. 6.02 x 1022",
            "C. 6.02 x1023",
            "D. 1.20 x 1024",
            "A. 3.01 x 1022", "A")),

        Questions( objective = Objective( "18", "", "", "18",
            "Consider the reaction represented by the following equation: xCH3OH + yO2 → 2CO2 + zH2O. The values of x,y and z respectively, are",
            "A. 2,3 and 4",
            "B. 2, 4 and 3",
            "C. 1,2 and 3",
            "D. 1, 3 and 5",
            "A. 2,3 and 4", "A")),


        Questions( objective = Objective( "19", "", "", "19",
            "The formula of mercury (l) dioxonitrate (III) is",
            "A. HgNO3",
            "B. Hg2NO2",
            "C. Hg2(NO2)2",
            "D. Hg(NO3)2",
            "C. Hg2(NO2)2", "C")),

        Questions( objective = Objective( "20", "", "", "",
            "A sample of a gas may be identified as chlorine if it turns",
            "A. damp blue litmus paper red",
            "B. lime water miky",
            "C. lead ethanoate paper black",
            "D. starch iodide paper blue-black",
            "D. starch iodide paper blue-black", "D")),

        Questions( objective = Objective( "21", "", "", "21",
            "A metal M forms two types of chlorine, MCl2 and MCl3 which of the following laws best explains the relationship between the chlorides? Law of",
            "A. conservation of mass",
            "B. definite proportion",
            "C. multiple proportion",
            "D. reciprocal proportion",
            "C. multiple proportion", "C")),

        Questions( objective = Objective( "22", "", "", "",
            "Which of the following metals would readily displace hydrogen from steam?",
            "A. Copper",
            "B. Lead",
            "C. Magnesium",
            "D. Silver",
            "C. Magnesium", "C")),


        Questions( objective = Objective( "23", "", "", "23",
            "The volume occupied by 0.4 g of hydrogen gas at s.t.p. is [H = 1. 00; Molar volume at s.t.p. = 22.4 dm3]",
            "A. 2.24 dm3",
            "B. 4.48dm3",
            "C. 22.4dm3",
            "D. 44.8dm 3",
            "D. 44.8dm 3", "D")),

        Questions( objective = Objective( "24", "", "", "",
            "When a substance changes directly from the solid state to the gaseous state without forming a liquid, the substance is said to",
            "A. condense",
            "B. evaporate",
            "C. sublime",
            "D. precipitate",
            "C. sublime", "C")),

        Questions( objective = Objective( "25", "", "", "25",
            "At ordinary temperature H2O is a liquid while H2S is a gas. This is because H2O has",
            "A. weak intermolecular forces holding its molecules together",
            "B. strong hydrogen bonds holding its molecules together",
            "C. induced dipole-induced dipole forces between its molecules",
            "D. ionic force between its molecules",
            "B. strong hydrogen bonds holding its molecules together", "B")),

        Questions( objective = Objective( "26", "", "", "",
            "The postulate that molecules are in constant random motion best explains why liquids",
            "A. can undergo solidification",
            "B. maintain their volumes",
            "C. are incompressible",
            "D. have no characteristic shape",
            "D. have no characteristic shape", "D")),

        Questions( objective = Objective( "27", "", "", "27",
            "Which of the following gases has the lowest rate of diffusion under the same condition? [H = 1.00; He = 4. 00; O = 16.0; CI = 35.5]",
            "A. CI2",
            "B. H2",
            "C. He",
            "D. O2",
            "A. CI2", "A")),

        Questions( objective = Objective( "28", "", "", "",
            "The energy evolved when magnesium burns in air is in the form of",
            "A. heat",
            "B. heat and sound",
            "C. light and heat",
            "D. sound",
            "C. light and heat", "C")),


        Questions( objective = Objective( "29", "", "", "29",
            "A substance L reacts with NH4NO3(aq) to generate ammonia gas. L is likely to be",
            "A. HCl",
            "B. NaOH",
            "C. CH3COOH",
            "D. CaSO4",
            "B. NaOH", "B")),


        Questions( objective = Objective( "30", "", "", "",
            "On heating, the following trioxocarbonate (IV) salts decompose to give solid residue except",
            "A. ammonium trioxocarbonate (IV)",
            "B. calcium trioxocarbonate (IV)",
            "C. lead (ll) trioxocarbonate(IV)",
            "D. zinc trioxocarbonate (IV)",
            "A. ammonium trioxocarbonate (IV)", "A")),

        Questions( objective = Objective( "31", "", "", "",
            "Which of the following pH values indicates that a solution is a strong base?",
            "A. 1",
            "B. 5",
            "C. 9",
            "D. 13",
            "D. 13", "D")),

        Questions( objective = Objective( "32", "", "", "32",
            "The hydrolysis of NH4CI gives",
            "A. an acidic solution",
            "B. an alkaline solution",
            "C. a buffer solution",
            "D. a neutral solution",
            "A. an acidic solution", "A")),


        Questions( objective = Objective( "33", "", "", "",
            "A spot of oil paint on a shirt can best be removed using",
            "A. brine",
            "B. detergent",
            "C. kerosine",
            "D. warm water",
            "C. kerosine", "C")),


        Questions( objective = Objective( "34", "", "", "34",
            "Consider the following solubility curves " +
                    "Which of the following deductions could be correctly made from the graph?",
            "A. The solubility of U is not affected by change in temperature",
            "B. The solubility of S decreases with increasing temperature",
            "C. T is most among the salts",
            "D. S is least soluble among the salts.",
            "A. The solubility of U is not affected by change in temperature", "A")),

            Questions( objective = Objective( "35", "", "", "35",
                "Consider the reaction represented by the following equation: CuO(s) + H2SO4(aq) → CuSO4(aq) + H2O(l). Which of the following factors will not affect the rate of the reaction?",
                "A. Particle size of CuO(s)",
                "B. Concentration of H2SO4(aq)",
                "C. Temperature of the reacting mixture",
                "D. Pressure of reaction system",
                "D. Pressure of reaction system", "D")),

            Questions( objective = Objective( "36", "", "", "36",
                "Use the graph to answer questions " +
                        "" +
                        "The activation energy for the reaction is ",

                "A. 40kj",
                "B. 60kj",
                "C. 80kj",
                "D.120kj",
                "A. 40kj", "A")),

            Questions( objective = Objective( "37", "", "", "37",
                "Use the graph to answer questions " +
                        "" +
                        "The type of reaction represented by the graph is",
                "A. endothermic",
                "B. exothermic",
                "C. catalytic",
                "D. spontaneous",
                "B. exothermic", "B")),

            Questions( objective = Objective( "38", "", "", "",
                "Which of the following devices function on redox reaction? l. Dry cell ll. Car battery III. Electric generator",
                "A. l and lll only",
                "B. ll and lll only",
                "C. l and ll only",
                "D. l, ll and lll",
                "C. l and ll only", "C")),

            Questions( objective = Objective( "39", "", "", "",
                "The oxidation number of Fe in [Fe(CN)6]3− is",
                "A. +3",
                "B. +2",
                "C. -2",
                "D. -3",
                "A. +3", "A")),

            Questions( objective = Objective( "40", "", "", "40",
                "Consider the following reaction equation: C16H34 → C5H12 + C11H22. The process represented by the equation is",
                "A. cracking",
                "B. fermentation",
                "C. polymerization",
                "D. reforming",
                "A. cracking", "A")),

            Questions( objective = Objective( "41", "", "", "41",
                "Consider the structure of organic compounds in the image below: " +
                        "Which of the following statements about the structure is not correct? They",
                "A. are geometric isomers",
                "B. are saturated hydrocarbons",
                "C. have similar physical properties",
                "D. are members of the same homologous",
                "B. are saturated hydrocarbons", "B")),

            Questions( objective = Objective( "42", "", "", "",
                "Which of the following substances would not produce ethanol when fermented?",
                "A. Cane sugar",
                "B. Glucose",
                "C. Starch",
                "D. Vinegar",
                "D. Vinegar", "D")),

            Questions( objective = Objective( "43", "", "", "",
                "An alkanol can be prepared by the reaction of an alkene with",
                "A. concentrated tetraoxosulphate (VI) acid",
                "B. bromine tetrachloroethane",
                "C. aqueous potassium tetraoxomanganate (VII)",
                "D. sodium hydroxide solution",
                "A. concentrated tetraoxosulphate (VI) acid", "A")),


            Questions( objective = Objective( "44", "", "", "44",
                "A compound contains 7.75% hydrogen, 37.21% carbon and 55.04% chlorine. " +
                        "Determine the empirical formula of the compound. [H =1.0; C=12:0; Cl=35.5]",
    "A. C3H3Cl",
    "B. C2H5Cl",
    "C. C3H8C",
    "D. C5H2Cl",
    "B. C2H5Cl", "B")),

    Questions( objective = Objective( "45", "", "", "54",
    "A tertiary alkanol has a molecular formula C4H10O. What is the structural formula of the compound?",
    "A. (CH 3)2CHCH2OH",
    "B. CH3CH2CH(OH)CH3",
    "C. (CH3)3COH",
    "D. CH3CH2CH2CH2OH",
    "C. (CH3)3COH", "C")),


    Questions( objective = Objective( "46", "", "", "",
    "Which of the following industrial processes depends on the action of enzymes?",
    "A. Liquefaction of air",
    "B. Manufacture of soap",
    "C. Brewing of beer",
    "D. Catalytic cracking",
    "C. Brewing of beer", "C")),

    Questions( objective = Objective( "47", "", "", "",
    "Which of the following pollutants is not usually recycled?",
    "A. Aluminium cans",
    "B. Glass bottles",
    "C. Nuclear wastes",
    "D. Paper wastes",
    "C. Nuclear wastes", "C")),

    Questions( objective = Objective( "48", "", "", "",
    "A metal that is widely used in the manufacture of paints and overhead electric cables is",
    "A. aluminium",
    "B. copper",
    "C. iron",
    "D. lead",
    "A. aluminium", "A")),

    Questions( objective = Objective( "49", "", "", "",
    "Brass is a mixture of",
    "A. Cu and Sn",
    "B. Cu and Zn",
    "C. Cu and Mg",
    "D. Cu and Pb",
    "B. Cu and Zn", "B")),


    Questions( objective = Objective( "50", "", "", "",
    "Which of the following substances is mainly responsible for the depletion of the ozone layer?",
    "A. Oxgyen",
    "B. Chlorofluorocarbon",
    "C. Carbon (ll) oxide",
    "D. Nitrogen (ll) oxide",
    "B. Chlorofluorocarbon", "B")),


    )
}