package com.example.repository.account

import com.example.repository.Objective
import com.example.repository.Questions

class Account2014Repo {

    val account2014 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "The source document used to make entries in the purchase day book is",
            "A. debt note",
            "B. credit note",
            "C. invoice",
            "D. receipt",
            "C. invoice", "C")
        ),

        Questions( objective = Objective( "2", "", "", "",
            "A book that contains individual accounts of suppliers is the",
            "A. purchase ledger",
            "B. general ledger",
            "C. nominal ledger",
            "D. sales ledger",
            "A. purchase ledger", "A")),

        Questions( objective = Objective( "3", "", "", "",
            "In the operation of an imprest of petty cash, the",
            "A. petty cashier pays all expenses",
            "B. petty cashier pays money to the accountant",
            "C. petty cashier regularly begins each period with the same amount of money",
            "D. main cashier accounts to the petty cashier for some experiences made by him",
            " C. petty cashier regularly begins each period with the same amount of money", "C")),

        Questions( objective = Objective( "4", "", "", "",
            "An example of a credit entry in a profit and loss account is",
            "A. carriage inwards",
            "B. carriage outwards",
            "C. discounts allowed",
            "D. discounts received",
            "D. discounts received", "D")),

        Questions( objective = Objective( "5", "", "", "",
            "Which of the following subsidiary books involves cash movements?",
            "A. sales day book",
            "B. purchases day book",
            "C. returns inwards book",
            "D. petty cash book",
            "D. petty cash book", "D")),

        Questions( objective = Objective( "6", "", "", "",
            "The accounting treatment for a dishonored cheque is; debit",
            "A. customer's account; credit bank account",
            "B. bank account; credit customer's account",
            "C. customer's account; credit sales account",
            "D. sales account; credit customer account",
            "C. customer's account; credit sales account", "C")),

        Questions( objective = Objective( "7", "", "", "",
            "Net turnover is referred to as",
            "A. purchases",
            "B. assets",
            "C. sales",
            "D. profits",
            "C. sales", "C")),

        Questions( objective = Objective( "8", "", "", "",
            "Which of the following transactions will result in disagreement between the cash book and the bank statements?",
            "A. selling of goods on credit to a customer",
            "B. withdrawal of goods by the proprietor for his personal use",
            "C. cheque paid directly into the bank account by a customer",
            "D. omission of purchases received from a supplier on credit",
            " C. cheque paid directly into the bank account by a customer", "C")),

        Questions( objective = Objective( "9", "", "", "",
            "Purchase account is overcast by ₦200, while wages account is undercast by ₦200. This is",
            "A. an error of omission",
            "B. a compensating error",
            "C. an error of commision",
            "D. an error of principal",
            "B. a compensating error", "B")),

        Questions( objective = Objective( "10", "", "", "",
            "Which of the following is used to record the disposal of a fixed asset?",
            "A. journal proper",
            "B. petty cash book",
            "C. sales day book",
            "D. purchase day book",
            "A. journal proper", "A")),

        Questions( objective = Objective( "11", "", "", "",
            "Use the table below to answer the questions " +
                    "The business make use of the straight line method for providing depreciation, the annual depreciation is",
        "A. ₦9,000",
        "B. ₦8,500",
        "C. ₦8,000",
        "D. ₦6,500",
        "C. ₦8,000 ", "C")),

    Questions( objective = Objective( "12", "", "", "",
    "Use the table below to answer the questions " +
            "The business make use of the straight line method for providing depreciation, the accumulated depreciation as at 31/12/2013 is",
    "A. ₦18,500",
    "B. ₦17,000",
    "C. ₦16,000",
    "D. ₦8,000",
    "C. ₦16,000", "C")),

    Questions( objective = Objective( "13", "", "", "",
    "An error of principle is made, if",
    "A. an entry has been made on the wrong class of account",
    "B. a transaction has been completely omitted",
    "C. an entry has been made on the wrong side of the two accounts concerned",
    "D. a transaction is entered in both accounts for the wrong amount",
    "A. an entry has been made on the wrong class of account", "A")),

    Questions( objective = Objective( "14", "", "", "",
    "Which of the following is entered in the general journal?",
    "A. purchase of goods",
    "B. sale of goods on credit",
    "C. returns inward",
    "D. acquisition of fixed assets",
    "D. acquisition of fixed assets", "D")),

    Questions( objective = Objective( "15", "", "", "",
    "The cost of carriage outward is classified as",
    "A. a selling and distribution expense",
    "B. an administrative expense",
    "C. a trading expense",
    "D. a finance expense",
    "A. a selling and distribution expense", "A")),

    Questions( objective = Objective( "16", "", "", "",
    "The purchase of ten ceiling fans by Akpan Electronic Enterprises will be recorded as",
    "A. an acquisition of fixed asset",
    "B. an expense in its general office expense account",
    "C. part of capital in the capital account",
    "D. an acquisition of stock",
    "D. an acquisition of stock", "D")),

    Questions( objective = Objective( "17", "", "", "",
    "Which of the following accounts would appear in the nominal ledger? i. Sanison's account(a debtor) ii. Motor vehicle account iii. Sales account iv. Rent and rates account",
    "A. i, ii and iii only",
    "B. i, iii and iv only",
    "C. ii, iii and iv only",
    "D. iii and iv only",
    " D. iii and iv only", "D")),

    Questions( objective = Objective( "18", "", "", "",
    "The sum of direct cost in a manufacturing account is",
    "A. production cost",
    "B. prime cost",
    "C. total cost",
    "D. finance cost",
    "B. prime cost", "B")),

    Questions( objective = Objective( "19", "", "", "",
    "Net profit in a business is",
    "A. the amount of money taken out of the business by the owner",
    "B. the cash in the business bank account",
    "C. the difference between sales and cost of sales",
    "D. sales revenue less cost of sales expenses",
    " D. sales revenue less cost of sales expenses", "D")),

    Questions( objective = Objective( "20", "", "", "",
    "An example of a self-balancing account is the",
    "A. suspense account",
    "B. credit account",
    "C. control account",
    "D. debtor account",
    "C. control account", "C")),

    Questions( objective = Objective( "21", "", "", "",
    "Use the following information to answer the question. " +
            "The total sales of a business was GHc 2,160,000 " +
            "The average markup for the year was 50%. " +
            "The gross profit is",
    "A. GHc2,160,000",
    "B. GHc1,440,000",
    "C. GHc 1,080,00",
    "D. GHc720,000",
    "C. GHc720,000", "C")),

    Questions( objective = Objective( "22", "", "", "",
    "Use the following information to the answer questions. " +
            "The total sales of a business was GHc 2,160,000 " +
            "The average markup for the year was 50%. " +
            "The cost sales is",
    "A. GHc2,160,000",
    "B. GHc1,440,000",
    "C. GHc1,080,000",
    "D. GHc720,000",
    "C. GHc1,080,000", "C")),


    Questions( objective = Objective( "23", "", "", "",
    "which of the following is not an administrative expenses in a manufacturing organization?",
    "A. discounts allowed",
    "B. office electricity",
    "C. stationery",
    "D. insurance",
    " D. insurance", "D")),

    Questions( objective = Objective( "24", "", "", "",
    "When an asset is sold, the entries for the accumulated depreciation are; debit",
    "A. assets disposal account; credit provision for depreciation account",
    "B. provision for depreciation account; credit asset disposal account",
    "C. fixed asset account; credit asset disposal account",
    "D. asset disposal account; credit fixed asset account",
    "B. provision for depreciation account; credit asset disposal account", "B")),

    Questions( objective = Objective( "25", "", "", "",
    "A petty cash account has an imprest of D28,000. The account has a debit balance of D5,000. How much cash is needed to restore the imprest?",
    "A. D33,000",
    "B. D28,000",
    "C. D23,000",
    "D. D5,000",
    "C. D23,000", "C")),

    Questions( objective = Objective( "26", "", "", "",
    "In a not-for-profit making organization, when the total income is less than the total expenditure, the difference is a",
    "A. surplus",
    "B. shortfall",
    "C. loss",
    "D. deficit",
    "D. deficit", "D")),

    Questions( objective = Objective( "27", "", "", "",
    "The accounting concept underlying the treatment of personal expenses of the business owner as drawing is",
    "A. periodicity",
    "B. accrual",
    "C. entity",
    "D. materiality",
    "C. entity", "C")),


    Questions( objective = Objective( "28", "", "", "",
    "Which of the following items is not contained in the Receipts and Payments Account?",
    "A. Subscription paid in advance",
    "B. stock paid for in advance",
    "C. outstanding wages and salaries",
    "D. donations",
    "C. outstanding wages and salaries", "C")),

    Questions( objective = Objective( "29", "", "", "",
    "The concept that states that a business should not lay claim to any profits before it is earned with reasonable certainty is",
    "A. consistency concept",
    "B. prudence concept",
    "C. accrual concept",
    "D. going concern concept",
    "C. accrual concept", "C")),

    Questions( objective = Objective( "30", "", "", "",
    "When shares are issued below their nominal value, the excess above the nominal value is",
    "A. credited to profit and loss account",
    "B. debited to share premium account",
    "C. credited to share capital account",
    "D. credited to share premium account",
    "D. credited to share premium account", "D")),

    Questions( objective = Objective( "31", "", "", "",
    "Shares issued below nominal value are referred to as shares at",
    "A. premium",
    "B. discount",
    "C. face value",
    "D. cumulative value",
    " B. discount", "B")),

    Questions( objective = Objective( "32", "", "", "",
    "Use the table below to answer the questions " +
            "The divisible profit is",
    "A. Le 14,000",
    "B. Le 12,000",
    "C. Le 10,000",
    "D. Le 8,000",
    " D. Le 8,000", "D")),

    Questions( objective = Objective( "33", "", "", "",
    "Use the table below to answer the questions " +
            "Aye’s share of profit is",
    "A. Le 6,000",
    "B. Le 4,800",
    "C. Le 4000",
    "D. Le 3,200",
    "D. Le 3,200", "D")),

    Questions( objective = Objective( "34", "", "", "",
    "Use the table below to answer the questions " +
            "Bee’s share of profit is",
    "A. Le 8,000",
    "B. Le 6,000",
    "C. Le 4,800",
    "D. Le 3,200",
    "C. Le 4,800", "C")),

    Questions( objective = Objective( "35", "", "", "",
    "The accounting ratio used to measure the average number of days for which suppliers remain unpaid is",
    "A. stock turnover",
    "B. creditor's payment period",
    "C. debtors collection period",
    "D. return on capital employed",
    "B. creditor's payment period", "B")),


    Questions( objective = Objective( "36", "", "", "",
    "When the purchase consideration exceeds the value of business, the difference is",
    "A. profit",
    "B. discount",
    "C. goodwill",
    "D. reserve",
    "C. goodwill", "C")),

    Questions( objective = Objective( "37", "", "", "",
    "The primary classification of government expenditure is based on",
    "A. programs",
    "B. fund",
    "C. activity",
    "D. project",
    "B. fund", "B")),

    Questions( objective = Objective( "38", "", "", "",
    "An example of input devices of a computer is",
    "A. an optical character reader",
    "B. a graph plotter",
    "C. a visual display unit",
    "D. a printer",
    "B. a graph plotter", "B")),

    Questions( objective = Objective( "39", "", "", "",
    "The accounting concept underlying the treatment of personal expenses of the business owner as drawing is",
    "A. periodicity",
    "B. accrual",
    "C. entity",
    "D. materiality",
    "D. materiality", "D")),

    Questions( objective = Objective( "40", "", "", "",
    "A company made a profit of N2,000.000 for the year and its net profit percentage is 25%. What is the total sales for the year?",
    "A. N8,000,000",
    "B. 6,000,000",
    "C. N800,000",
    "D. N500,000",
    "A. N8,000,000", "A")),

    Questions( objective = Objective( "41", "", "", "",
    "Which of the following information is recorded in the returns outwards book?",
    "A. goods purchased on credit and subsequently returned to suppliers",
    "B. fixed asset bought on credit and subsequently returned to supplier",
    "C. cash payment received from a customer and subsequently returned to supplier",
    "D. goods sold to a customer and subsequently returned to the business",
    "D. goods sold to a customer and subsequently returned to the business", "D")),

    Questions( objective = Objective( "42", "", "", "",
    "Use the table below to answer the questions " +
            "Calculate the stock figure to be included in the balance sheet at the year end",
    "A. D408,000",
    "B. D346,000",
    "C. D284,000",
    "D. D62,000",
    "C. D284,000", "C")),


    Questions( objective = Objective( "43", "", "", "",
    "Use the table below to answer the questions " +
            "The concept applied in calculating the stock figure to be included in the balance sheet at the year end is",
    "A. matching",
    "B. consistency",
    "C. prudence",
    "D. entiti",
    " C. prudence", "C")),

    Questions( objective = Objective( "44", "", "", "",
    "subscription in advance is classified in the balance sheet as",
    "A. an asset",
    "B. a liability",
    "C. a deficit",
    "D. a surplus",
    " B. a liability", "B")),

    Questions( objective = Objective( "45", "", "", "",
    "Which of the following item is not treated in the profit and loss account?",
    "A. office expenses",
    "B. salaries and allowances",
    "C. carriage inwards",
    "D. discounts allowed",
    "C. carriage inwards", "C")),

    Questions( objective = Objective( "46", "", "", "",
    "The document prepared by a local/district government to present its annual estimates for a planning period is",
    "A. a balance sheet",
    "B. a budget",
    "C. an income and expendiure account",
    "D. a cash bppk",
    " B. a budget", "B")),

    Questions( objective = Objective( "47", "", "", "",
    "A manufacturing account is drawn up by",
    "A. firms providing personal services",
    "B. firms engaged solely in buying and selling of goods",
    "C. firms which makes and sell articles",
    "D. non-trading organization",
    "D. non-trading organization", "D")),

    Questions( objective = Objective( "48", "", "", "",
    "Which of the following is not a factory overhead cost? ",
    "A. manufacturing wages",
    "B. factory rent",
    "C. depreciation of machinery",
    "D. salary of factory guard",
    " A. manufacturing wages", "A")),

    Questions( objective = Objective( "49", "", "", "",
    "A collection of fields relating to one logically definable unit of business information is known as",
    "A. database",
    "B. character",
    "C. byte",
    "D. record",
    " D. record", "D")),

    Questions( objective = Objective( "50", "", "", "",
    "The principle of double entry bookkeeping states that",
    "A. every debtor must have a creditor",
    "B. every account debited must be immediately credited",
    "C. for every debit entry, there must be a corresponding credit entry",
    "D. for every double debit, there must be a double credit",
    "C. for every debit entry, there must be a corresponding credit entry", "C")),

    )
}