package com.example.repository.account

import com.example.repository.Objective
import com.example.repository.Questions

class Account2013Repo {
    val account2013 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "The distinguishing feature between a two-column cash book is",
            "A. discount column",
            "B. cash column",
            "C. bank column",
            "D. ledger folio",
            "A. discount column", "A")
        ),



        Questions( objective = Objective( "2", "", "", "",
            "The lodgement of business cash into the business bank account is an example of",
            "A. contra entry",
            "B. bank reconciliation",
            "C. self-balancing ledger",
            "D. reversal entry",
            "A. contra entry", "A")),

        Questions( objective = Objective( "3", "", "", "",
            "A credit balance is",
            "A. a liability or an expense",
            "B. a liability or an income",
            "C. an expenditure or an income",
            "D. an asset or an expense",
            "B. a liability or an income", "B")),

        Questions( objective = Objective( "4", "", "", "",
            "Which of the following is not a characteristic of trial balance?",
            "A. it has columns for debit and credit balances",
            "B. total of debit balance equals total of credit balance",
            "C. it is a statement",
            "D. it is an account",
            "D. it is an account", "D")),


        Questions( objective = Objective( "5", "", "", "",
            "The capital of a sole trader changes as a result of",
            "A. paying wages by cash",
            "B. equipment purchased by cheque",
            "C. drawings by cheque",
            "D. purchase on credit",
            " C. drawings by cheque", "C")),


        Questions( objective = Objective( "6", "", "", "",
            "The order of financial accounting process involves i. recording ii. presenting iii. collecting iv. analyzing",
            "A. I, ii, iii and iv",
            "B. ii, iii, i and iv",
            "C. iii, i, ii and iv",
            "D. iv, iii, ii and iv",
            "C. iii, i, ii and iv", "C")),

        Questions( objective = Objective( "7", "", "", "",
            "A dishonored cheque is",
            "A. debited in cash book",
            "B. credited in the cash book",
            "C. double entry in the cash book",
            "D. credited in the bank book",
            "B. credited in the cash book", "B")),

        Questions( objective = Objective( "8", "", "", "",
            "A petty cashier received a float of GHC 84. The imprest is",
            "A. GHC 204",
            "B. GHC 120",
            "C. GHC 84",
            "D. GHC 36",
            "B. GHC 120", "B")),

        Questions( objective = Objective( "9", "", "", "",
            "Which of the following is not a book of original entry?",
            "A. cash book",
            "B. purchases ledger ",
            "C. returns outwards journal",
            "D. general journal",
            "B. purchases ledger ", "B")),

        Questions( objective = Objective( "10", "", "", "",
                " Use the table below to answer the question " +
                        "The current ratio is?",
        "A. 1.87 : 1",
        "B. 1 : 1.87",
        "C. 1 : 2",
        "D. 2 : 1",
        "A. 1.87 : 1", "A")),

    Questions( objective = Objective( "11", "", "", "",
    "Use the table below to answer the question" +
            "The capital employed is",
    "A. ₦ 740,000",
    "B. ₦ 580,000",
    "C. ₦ 370,000",
    "D. ₦ 280, 000",
    "B. ₦ 580,000", "B")),

    Questions( objective = Objective( "12", "", "", "",
    "Use the table below to answer the question" +
     "The returns on capital employed is",
    "A. 17.2%",
    "B. 16.2%",
    "C. 15.2%",
    "D. 11.2%",
    "B. 16.2%", "B")),

    Questions( objective = Objective( "13", "", "", "",
    "The double entry principle states that",
    "A. every debit entry must have a corresponding credit entry",
    "B. every credit entry must have a corresponding double entry",
    "C. every debit must must have a corresponding double entry",
    "D. every assets must have a corresponding liability",
    "A. every debit entry must have a corresponding credit entry", "A")),

    Questions( objective = Objective( "14", "", "", "",
    "Which of the following is a nominal account?",
    "A. machinery account",
    "B. drawings account",
    "C. debtors account",
    "D. wages account",
    "D. wages account", "D")),

    Questions( objective = Objective( "15", "", "", "",
    "Reserves account is kept in the",
    "A. private ledger",
    "B. creditors ledger",
    "C. nominal ledger",
    "D. debtors ledger",
    "C. nominal ledger", "C")),

    Questions( objective = Objective( "16", "", "", "",
    "An advantage of control account is ",
    "A. location figures",
    "B. adding figures",
    "C. changing figure",
    "D. locating errors",
    "D. locating errors", "D")),

    Questions( objective = Objective( "17", "", "", "",
    "The accumulative fund of a not-for-profit making organization is",
    "A. a fixed asset",
    "B. a current asset",
    "C. a liability",
    "D. capital",
    "D. capital", "D")),

    Questions( objective = Objective( "18", "", "", "",
    "A business is treated as being separated from owners. This statement is emphasized by",
    "A. consistency concept",
    "B. realization concept",
    "C. going concern concept",
    "D. business entity concept",
    "D. business entity concept", "D")),

    Questions( objective = Objective( "19", "", "", "",
    "Which of the following is recorded on the debit side of the Trial Balance?",
    "A. bank overdrafted",
    "B. returns outwards",
    "C. purchases",
    "D. capital",
    " C. purchases","C")),

    Questions( objective = Objective( "20", "", "", "",
    "Use the table below to answer the question" +
            "Purchases for the year is",
    "A. D32,880",
    "B. D32,780",
    "C. D32,460",
    "D. D31,960",
    "C. D32,460", "C")),

    Questions( objective = Objective( "21", "", "", "",
    "Use the table below to answer the question " +
            "Sales for the year is",
    "A. D42,795",
    "B. D41,865",
    "C. D41,580",
    "D. D39,720",
    "C. D41,580", "C")),


    Questions( objective = Objective( "22", "", "", "",
    "Which of the following is determined in the Trading account?",
    "A. Factory Overheads",
    "B. Cost of goods sold",
    "C. Prime cost",
    "D. Net profit",
    "B. Cost of goods sold", "B")),

    Questions( objective = Objective( "23", "", "", "",
    "Cash receipts and payments involving discounts are entered in",
    "A. three-column cash book",
    "B. two-column cash book",
    "C. analytical cash book",
    "D. petty cash book",
    "A. three-column cash book", "A")),

    Questions( objective = Objective( "24", "", "", "",
    "The minimum number of persons required to form a partnership business is",
    "A. 2",
    "B. 3",
    "C. 5",
    "D. 10",
    "A. 2", "A")),


    Questions( objective = Objective( "25", "", "", "",
    "Which of the following accounts has credit balance?",
    "A. return inwards account",
    "B. machinery account",
    "C. sales account",
    "D. cash account",
    " C. sales account", "C")),

    Questions( objective = Objective( "26", "", "", "",
    "The accounting principle that states that, In the preparation of account statements, revenues are recognized as soon as goods is passed on to the customer is the",
    "A. materiality concept",
    "B. matching concept",
    "C. constituency concept",
    "D. realization concept",
    "B. matching concept", "B")),


    Questions( objective = Objective( "27", "", "", "",
    "Agreement between partners is contained in the partnership",
    "A. act",
    "B. deeds",
    "C. accord",
    "D. deal",
    "B. deeds", "B")),

    Questions( objective = Objective( "28", "", "", "",
    "A low current ratio in business indicates that the business is",
    "A. faced long term loan repayment problem",
    "B. efficient in the utilization of its resources",
    "C. unable to pay its bills on time",
    "D. growing its net assets effectively",
    " A. faced long term loan repayment problem", "A")),

    Questions( objective = Objective( "29", "", "", "",
    "Which of following is a recurrent expenditure in public sector accounting?",
    "A. purchase of vehicles",
    "B. purchase of drugs",
    "C. construction of bore holes",
    "D. construction of buildings",
    " B. purchase of drugs", "B")),

    Questions( objective = Objective( "30", "", "", "",
    "In departmental accounts, administrative expenses are recorded in the",
    "A. Trading account",
    "B. balance sheets",
    "C. profit and loss account",
    "D. profit and loss appropriation account",
    "C. profit and loss account", "C")),

    Questions( objective = Objective( "31", "", "", "",
    "The public account committee is an organ of",
    "A. military regime",
    "B. parliament regime",
    "C. presidency",
    "D. councilors",
    " C. presidency", "C")),

    Questions( objective = Objective( "32", "", "", "",
    "Use the table below to answer the question" +
            "The balance at the end of the period is",
    "A. Le 270,000",
    "B. Le 139, 000",
    "C. Le 131,000",
    "D. Le 120,000",
    "C. Le 131,000", "C")),

    Questions( objective = Objective( "33", "", "", "",
    "Use the table below to answer the question " +
            "The total expenditure for the period is",
    "A. Le 319,000",
    "B. Le 270,000",
    "C. Le 139,000",
    "D. Le 109,000",
    " D. Le 109,000", "D")),

    Questions( objective = Objective( "34", "", "", "",
    "Which of the following is not an item on the credit side of the purchases ledger control account?",
    "A. cash received",
    "B. cash payment",
    "C. contra settlement",
    "D. cheque payment",
    " A. cash received", "A")),

    Questions( objective = Objective( "35", "", "", "",
    "When a business is purchased from a sole trader, the excess of the purchase price over the net assets is",
    "A. reserve",
    "B. goodwill",
    "C. freehold",
    "D. valuation price",
    " B. goodwill", "B")),

    Questions( objective = Objective( "36", "", "", "",
    "A set of instrument or programs which controls the operation of a computer is",
    "A. software",
    "B. hardware",
    "C. monitor",
    "D. keyboard",
    " A. software", "A")),

    Questions( objective = Objective( "37", "", "", "",
    "The process of detecting, tracing and eliminating errors in a computer program is",
    "A. reproduction",
    "B. debugging",
    "C. sorting",
    "D. retrieving",
    "B. debugging", "B")),

    Questions( objective = Objective( "38", "", "", "",
    "In a non-for-profit making organization, the cash book is referred to as",
    "A. income and expenditure account",
    "B. receipts and payments account",
    "C. two column cashbook",
    "D. petty cash book",
    "B. receipts and payments account", "B")),

    Questions( objective = Objective( "39", "", "", "",
    "When the going concern concept is no longer applicable, the fixed assets are recorded at their",
    "A. net book value",
    "B. realizable value",
    "C. gross value",
    "D. revalued amount",
    "D. revalued amount", "D")),

    Questions( objective = Objective( "40", "", "", "",
    "Use the table below to answer the question " +
            "The cost of raw material consumed is ",
    "A. GHc 58,000",
    "B. GHc 52,500",
    "C. GHc 52,000",
    "D. GHc 50,000",
    "C. GHc 52,000", "C")),

    Questions( objective = Objective( "41", "", "", "",
    "Use the table below to answer the question " +
            "The prime cost is",
    "A. GHc 64,500",
    "B. GHc 64,000",
    "C. GHc 58,500",
    "D. GHc 52,500",
    "B. GHc 64,000", "B")),


    Questions( objective = Objective( "42", "", "", "",
    "Which of the following relates to the essence of partnership? To",
    "A. run a charity organization",
    "B. pursue a social objective",
    "C. form a business for profit",
    "D. run a religious objective",
    "C. form a business for profit", "C")),

    Questions( objective = Objective( "43", "", "", "",
    "The basic assumption which underline the preparation of periodic financial statement is known as accounting",
    "A. bases",
    "B. techniques",
    "C. concepts",
    "D. method",
    "C. concepts", "C")),

    Questions( objective = Objective( "44", "", "", "",
    "Upon the dissolution of partnership business, the party to be settled first out of the proceeds realized is",
    "A. unsecured creditors",
    "B. partner's loan and advances",
    "C. secured creditors",
    "D. partners' capital",
    "B. partner's loan and advances", "B")),

    Questions( objective = Objective( "45", "", "", "",
    "Stock account is a type of",
    "A. nominal account",
    "B. personal account",
    "C. real account",
    "D. fixed assets account",
    "C. real account", "C")),

    Questions( objective = Objective( "46", "", "", "",
    "At the end of trading period, cost of goods sold is debited to the trading account while cost of services is debited to the",
    "A. balance sheet",
    "B. manufacturing account",
    "C. trading account",
    "D. profit and loss account",
    "D. profit and loss account", "D")),

    Questions( objective = Objective( "47", "", "", "",
    "Which of the following is not part of prime cost of production?",
    "A. depreciation of factory equipment",
    "B. direct expenses",
    "C. direct wages",
    "D. carriage on raw materials",
    " A. depreciation of factory equipment", "A")),

    Questions( objective = Objective( "48", "", "", "",
    " Excess of current assets over current liabilities is",
    "A. deferred capital",
    "B. nominal capital",
    "C. working capital",
    "D. authorized capital",
    "C. working capital", "C")),

    Questions( objective = Objective( "49", "", "", "",
    "A statement showing a trader's financial position as at a particular date is an",
    "A. trading account",
    "B. profit and loss account",
    "C. balance sheet",
    "D. appropriation account",
    "C. balance sheet", "C")),

    Questions( objective = Objective( "50", "", "", "",
    "A trading account is prepared to disclose the",
    "A. net profile or loss for the year",
    "B. gross profit or loss for the year",
    "C. accumulated fund for the year",
    "D. gross profit on manufacturing",
    "B. gross profit or loss for the year", "B")),


    )
}