package com.example.repository.mathematics


import com.example.repository.Objective
import com.example.repository.Questions


class Maths2012Repo {

    val maths2012 = listOf<Questions>(

        Questions( objective = Objective( "1", "", "", "",
            "Express 302.10495 correct to five significant figures",
            "A. 302.10",
            "B. 302.11",
            "C. 302.105",
            "D. 302.1049",
            "A. 302.10",
            "A",
        )
        ),

        Questions( objective = Objective( "2", "", "", "2",
            "Simplify; ",
            "A. √2",
            "B. √5",
            "C. √22",
            "D. 2√5",
            "D. 2√5", "D")),

        Questions( objective = Objective( "3", "", "", "",
            "In 1995, the enrollment of two schools X and Y were 1,050 and 1,190 respectively. Find the ration of the enrollments of X and Y",
            "A. 50:11",
            "B. 15:17",
            "C. 13:55",
            "D. 12:11",
            "B. 15:17", "B")),

        Questions( objective = Objective( "4", "", "", "4",
            "",
            "A. 1011",
            "B. 10011",
            "C. 100011",
            "D. 11001",
            "C. 100011", "C")),

        Questions( objective = Objective( "5", "", "", "5",
            "",
            "A. 30",
            "B. 16",
            "C. -16",
            "D. -30",
            "C. -16", "C")),

        Questions( objective = Objective( "6", "", "", "",
            "Mr. Manu travelled from Accra to Pamfokromb a distance of 720km in 8 hours. What will be his speed in m/s?",
            "A. 25m/s",
            "B. 150m/s",
            "C. 250m/s",
            "D. 500m/s",
            "A. 25m/s", "A")),

        Questions( objective = Objective( "7", "", "", "",
            "If N2,500.00 amounted to N3,50.00 in 4 years at simple interest, find the rate at which the interest was charged",
            "A. 5%",
            "B. 712%",
            "C. 8%",
            "D. 10%",
            "D. 10%", "D")),

        Questions( objective = Objective( "8", "", "", "8",
            "Solve for x in the equation; ",
            "A. 5",
            "B. 4",
            "C. 3",
            "D. 1",
            "A. 5", "A",)),

        Questions( objective = Objective( "9", "", "", "9",
            "Simplify: ",
            "",
            "",
            "C. 6(3k - 1)",
            "D. 6(1 - 3k)",
            "C. 6(3k - 1)", "C",)),

        Questions( objective = Objective( "10", "", "", "",
            "Represent in inequality -7 < 4x + 9 ≤ 13 on a number line ",
            "A",
            " B",
            "C",
            " D",
            "B", "B",)),

        Questions( objective = Objective( "11", "", "", "11",
            "Make p the subject of the relation: ",
            "A. p = 2q − rs6",
            "B. p = 2qr - sr - 3",
            "C. p = 2qr − s6",
            "D. p = (2qr − rs) / 6",
            "D. p = (2qr − rs) / 6", "D")),

        Questions( objective = Objective( "12", "", "", "",
            "If x + y = 2y - x + 1 = 5, find the value of x",
            "A. 3",
            "B. 2",
            "C. 1",
            "D. -1",
            " A. 3", "A")),

        Questions( objective = Objective( "13", "", "", "",
            "The sum of 12 and one third of n is 1 more than twice n. Express the statement in the form of an equation",
            "A. 12n - 6 = 0",
            "B. 3n - 12 = 0",
            "C. 2n - 35 = 0",
            "D. 5n - 33 = 0",
            "D. 5n - 33 = 0", "D")),

        Questions( objective = Objective( "14", "", "", "14",
            "Solve the inequality:",
            "A. m ≤ 5/4",
            "B. m ≥ 5/4",
            "C. m ≤ −1/11",
            "D. m ≥ −1/11",
            "D. m ≥ −1/11", "D")),

        Questions( objective = Objective( "15", "", "", "",
            "The curved surface area of a cylindrical tin is 704cm2. If the radius of its base is 8cm, find the height. [Take π=227]",
            "A. 14cm",
            "B. 9cm",
            "C. 8cm",
            "D. 7cm",
            "A. 14cm", "A")),

        Questions( objective = Objective( "16", "", "", "16",
            "The lengths of the minor and major arcs 54cm and 126cm respectively. Calculate the angle of the major sector",
            "A. 360",
            "B. 252",
            "C. 246",
            "D. 234",
            "B. 252o", "B")),

        Questions( objective = Objective( "17", "", "", "",
            "A sector of a circle which subtends 172o at the centre of the circle ha a perimeter of 600cm. Find, correct to the nearest cm, the radius of the circle. (π =22/7)",
            "A. 120cm",
            "B. 116cm",
            "C. 107cm",
            "D. 100cm",
            "A. 120cm", "A")),

        Questions( objective = Objective( "18", "", "", "18",
            "",
        "A. 1.32m",
        "B. 6.32m",
        "C. 9.32m",
        "D. 17.32",
        "C. 9.32m", "C")),


    Questions( objective = Objective( "19", "", "", "19",
    "In △XYZ, /XY/ = 8cm, /YZ/ = 10cm and /XZ/ = 6cm. Which of these relation is true?",
    "A. /XY/ + /YZ/ = /XZ/",
    "B. /XY/ - /YZ/ = /XZ/",
    "C. /XY/2 = /Y/2 - /XY/2",
    "D. /YZ/2 = /XZ/2 + /XY/2",
    "C. /YZ/2 = /XZ/2 - /XY/2", "C")),

    Questions( objective = Objective( "20", "", "", "20",
    "",
    "A. 108",
    "B. 172",
    "C. 130",
    "D. 50",
    "B. 172", "B")),

    Questions( objective = Objective( "21", "", "", "",
    "The diagram is a circle centre O. If < SPR = 2m and < SQR = n, express m in terms of n",
    "A. m = n/2",
    "B. m = 2n",
    "C. m = n - 2",
    "D. m = n + 2",
    "A. m = n/2", "A")),

    Questions( objective = Objective( "22", "", "", "22",
    "",
    "A. 150",
    "B. 110",
    "C. 100",
    "D. 95",
    "C. 100o", "C")),

    Questions( objective = Objective( "23", "", "", "",
    """
    Is the diagram, MN, PQ and RS are three intersecting straight lines. Which of the following statements is/are true?
    i. t = y
    ii. x + y + z + m = 180
    ii. x + m + n = 180
    iv. x + n = m + z
    """.trimIndent() ,
    "A. i and iv",
    "B. ii",
    "C. iii",
    "D. iv",
    "C. iii", "C")),

    Questions( objective = Objective( "24", "", "", "24",
    "",
    "A. 85",
    "B. 75",
    "C. 65",
    "D. 45",
    " D. 45o", "D")),

    Questions( objective = Objective( "25", "", "", "25",
    "A kite flies on a taut string of length 50m inclined at tan angle 54 to the horizontal ground. The height of the kite above the ground is",
    "A. 50 tan 30",
    "B. 50 sin 54",
    "C. 50 tan 54",
    "D. 50 sin 36",
    "B. 50 sin 54", "B")),

    Questions( objective = Objective( "26", "", "", "26",
    "The position of three ships P,Q and R at sea are illustrated in the diagram. The arrows indicated the North direction. The bearing of Q from P is 050o and < PQR = 72o. Calculate the bearing of R and Q",
    "A. 155",
    "B. 80",
    "C. 158",
    "D. 91",
    "C. 158", "C")),

    Questions( objective = Objective( "27", "", "", "",
    "Given that the mean of the scores 15, 21, 17, 26, 18 and 29 is 21, calculate the standard deviation of the scores",
    "A.√10",
    "B. 4",
    "C. 5",
    "D. √30",
    "C. 5", "C")),


    Questions( objective = Objective( "28", "", "", "",
    "A bag contains 4 red and 6 black balls of the same size. If the balls are shuffled briskly and two balls are drawn one after the other without replacement, find the probability of picking balls of different colours",
    "A. 8/15",
    "B. 13/25",
    "C. 11/15",
    "D. 13/15",
    "A. 8/15", "A")),

    Questions( objective = Objective( "29", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. How many students are in the class?",
    "A. 10",
    "B. 24",
    "C. 25",
    "D. 30",
    "C. 25", "C")),


    Questions( objective = Objective( "30", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. Calculate the mean of the distribution.",
    "A. 6.0",
    "B. 3.0",
    "C. 2.4",
    "D. 1.8",
    "C. 2.4", "C")),


    Questions( objective = Objective( "31", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. What is the median of the distribution?",
    "A. 2",
    "B. 4",
    "C. 6",
    "D. 8",
    "A. 2", "A")),

    Questions( objective = Objective( "32", "", "", "",
    "Which of these statements about y =√ 8m  is correct?",
    "A. log y = log 8 x log √m",
    "B. log y = 3 log 2 x 1/2 log m",
    "C. log y = 3 log 2 - 1/2 log m",
    "D. log y = 3 log 2 + 1/2 log m",
    "D. log y = 3 log 2 + 1/2 log m", "D"
    )),

    Questions( objective = Objective( "33", "", "", "33",
    "",
    "A. 1 ",
    "B. 212",
    "C. 3 ¾",
    "D. 5",
    "C. 3 ¾", "C")),

    Questions( objective = Objective( "34", "", "", "34",
    "",
    "A. 3xyy",
    "B. x−4yy",
    "C. 4y−x/y",
    "D. 3 - x−yy",
    "C. 4y−x/y", "C")),

    Questions( objective = Objective( "35", "", "", "35",
    "",
    "A. -16",
    "B. - 12",
    "C. -1",
    "D. -116",
    "D. -116", "D")),

    Questions( objective = Objective( "36", "", "", "36",
    "",
    "A. 51",
    "B. 54",
    "C. 56",
    "D. 68",
    "B. 54", "B")),

    Questions( objective = Objective( "37", "", "", "",
    "If p = {prime factors of 210} and Q = {prime less than 10}, find p ∩ Q",
    "A. {1,2, 3}",
    "B. {2, 3, 5}",
    "C. {1, 3, 5,7}",
    "D. {2,3,5,7}",
    "D. {2,3,5,7}", "D")),


    Questions( objective = Objective( "38", "", "", "",
    "Alfred spent 14 of his money on food, 13 on clothing and save the rest. If he saved N72,20.00, how much did he spend on food?",
    "A. N43,200.00",
    "B. N43,000.00",
    "C. N42,200.00",
    "D. N40,000.00",
    "A. N43,200.00", "A")),


    Questions( objective = Objective( "39", "", "", "39",
    "Solve (27125)-13 x (49)12",
    "A. 10/9",
    "B. 9/10",
    "C. ⅖",
    "D. 12/15",
    "A. 10/9", "A")),


    Questions( objective = Objective( "40", "", "", "",
    "The sum of the interior angles of regular polygon is 1800. How many sides has the polygon?",
    "A. 16",
    "B. 12",
    "C. 10",
    "D. 8",
    "B. 12", "B")),

    Questions( objective = Objective( "41", "", "", "41",
    "The diagram is a circle with centre O. PRST are points on the circle. Find the value of < PRS",
    "A. 144",
    "B. 72",
    "C. 40",
    "D. 36",
    "D. 36", "D")),

    Questions( objective = Objective( "42", "", "", "",
    "The diagram is a circle of radius |QR| = 4cm. R¯ is a tangent to the circle at R. If TPO = 120, find |PQ|.",
    "A. 2.32cm",
    "B. 1.84cm",
    "C. 0.62cm",
    "D. 0.26cm",
    "C. 0.62cm", "C")),

    Questions( objective = Objective( "43", "", "", "",
    "If x and y are variables and k is a constant, which of the following describes an inverse relationship between x and y?",
    "A. y = kx",
    "B. y = k / x",
    "C. y = k√x",
    "D. y = x + k",
    "B. y = kx", "B"
    )),

    Questions( objective = Objective( "44", "", "", "44",
    "",
    "A. 65",
    "B. 45",
    "C. 25",
    "D. 19",
    "D. 19", "D")),

    Questions( objective = Objective( "45", "", "", "45",
    "The graph is that of y = 2x2 - 5x - 3. For what value of x will y be negative? ",
    "A. -1/2≤x < 3",
    "B. -1/2<x≤3",
    "C. -1/2<x<3",
    "D. -1/2≤x≤3",
    "C. -1/2<x<3", "C")),

    Questions( objective = Objective( "46", "", "", "46",
    "The graph is that of y = 2x2 - 5x - 3. What is the gradient of y = 2x2 - 5x - 3 at the point x = 4?",
    "A. 11.1",
    "B. 10.5",
    "C. 10.3",
    "D. 9.9",
    "A. 11.1", "A")),

    Questions( objective = Objective( "47", "", "", "47",
    "The diagram is a polygon. Find the largest of its interior angles",
    "A. 300",
    "B. 100",
    "C. 120",
    "D. 150",
    " D. 150o", "D")),

    Questions( objective = Objective( "48", "", "", "48",
    "The volume of a cuboid is 54cm3. If the length, width and height of the cuboid are in the ratio 2:1:1 respectively, find its total surface area",
    "A. 108cm",
    "B. 90cm",
    "C. 80cm",
    "D. 72cm",
    "B. 90cm", "B")),

    Questions( objective = Objective( "49", "", "", "49",
    "A side and a diagonal of a rhombus are 10cm and 12cm respectively, Find its area",
    "A. 20cm",
    "B. 24cm",
    "C. 48cm",
    "D. 96cm",
    "D. 96cm2", "D")),


    Questions( objective = Objective( "50", "", "", "50",
    "",
    "A. 16x2y(2 - 3xy2)",
    "B. 8xy(4x - 6x2y2)",
    "C. 8x2y(4 - 6xy2)",
    "D. ",
    "A. 16x2y(2 - 3xy2)", "A")),

    )


}
