package com.example.repository.biology

import com.example.repository.Objective
import com.example.repository.Questions


class Biology2017Repo {

    val biology2017 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "Which of the following groups of animals do not possess a nervous system?",
            "A. Porifera",
            "B. Cnidaria",
            "C. Platyheminthes",
            "D. Nematoda",
            "A. Porifera", "A")),

        Questions( objective = Objective( "2", "", "", "",
            "The structural similarities in Paramecium and Euglena are in the",
            "A. shape of locomotory organs",
            "B. blunt anterior and pointed posterior",
            "C. presence of micro and mega nuclei in both",
            "D. presence of anterior and posterior contractile vacuoles",
            "B. blunt anterior and pointed posterior", "B")),

        Questions( objective = Objective( "3", "", "", "",
            "Which of the following organisms cannot exist freely on its own?",
            "A. Chlamydomonas",
            "B. Amoeba",
            "C. Paramecium",
            "D. Plasmodium",
            "D. Plasmodium", "D")),

        Questions( objective = Objective( "4",
            "The diagram below is an illustration of an Athropod. Study it and answer question 4", "", "",
            "The arthropod in the diagram is not an insect beacuse it",
            "A. Has a big head which is almost equal to the thorax",
            "B. has eight legs and no wings",
            "C. does not have visible eyes on it head",
            "D. has head thorax and abdomen",
            "B. has eight legs and no wings", "B")),

        Questions( objective = Objective( "5", "", "", "",
            "Which of the following cell organelles is the site for the production of ATP?",
            "A. Lysosome",
            "B. Nucleus",
            "C. Mitochondrion",
            "D. Ribosome",
            "C. Mitochondrion", "C")),

        Questions( objective = Objective( "6", "", "", "",
            "An example of osmosis in plants is the",
            "A. movement of water through the xylem",
            "B. loss of water vapour from the stomata",
            "C. translocation of food through the phloem",
            "D. absorption of water from the soil by the root",
            "D. absorption of water from the soil by the root", "D")),


        Questions( objective = Objective( "7", "", "", "",
            "The organism that can carry out both autotropic and heterotrophic modes of nutritions is",
            "A. Chlamydomonas",
            "B. Eudorina",
            "C. Euglena",
            "D. Spirogyra",
            "C. Euglena", "C")),


        Questions( objective = Objective( "8", "", "", "",
            "The diagram above illustrates a part of the human skeleton. It represents the bones of the",
            "A. upper arm",
            "B. lower arm",
            "C. upper leg",
            "D. lower leg",
            " D. lower leg", "D")),


        Questions( objective = Objective( "9", "", "", "",
            "Which of the labelled parts of the diagram of the part of the human skeleton articulates with the head of the trochlea to form a hinge joint?",
            "A. I",
            "B. II",
            "C. III",
            "D. IV",
            "B. II", "B")),


        Questions( objective = Objective( "10", "", "", "",
            "The diagram above illustrates a part of the human skeleton. The labelled part that provides surface for the attachment of the triceps is",
            "A. I",
            "B. II",
            "C. III",
            "D. IV",
            " C. III", "C")),


        Questions( objective = Objective( "11", "", "", "",
            "The diagram above illustrates the transverse section of a",
            "A. dicotyledonous root",
            "B. monocotyledonous root",
            "C. dicotyledonous stem",
            "D. monocotyledonous stem",
            "C. dicotyledonous stem", "C")),


        Questions( objective = Objective( "12", "", "", "",
            "Which of the following actions does not occur during exhalation in man?",
            "A. Thoracic cavity decreases in volume",
            "B. Diaphragm flattens",
            "C. Ribs move down and in",
            "D. Air pressure increases in the thoracic cavity",
            "B. Diaphragm flattens", "B")),


        Questions( objective = Objective( "13", "", "", "",
            "The diagram above is an illustration of the urinary tubule in a mammal. Which of the following substances is found in the part labelled II only?",
            "A. Lipid",
            "B. protein",
            "C. salts",
            "D. water",
            "C. salts", "C")),

        Questions( objective = Objective( "14", "", "", "",
            "The diagram above is an illustration of the urinary tubule in a mammal. The part which contains lowest concentration of urea is labelled",
            "A. I",
            "B. II",
            "C. III",
            "D. IV",
            "C. III", "C")),


        Questions( objective = Objective( "15", "", "", "",
            "The diagram above is an illustration of the urinary tubule in a mammal. Which of the following substances is greater in concentration in the part labelled IV when compared to that part labelled I?",
            "A. Lipid",
            "B. Glucose",
            "C. Urea",
            "D. Uric acid",
            "C. Urea", "C")),

        Questions( objective = Objective( "16", "", "", "",
            "Deamination of amino acids in the liver produces ",
            "A. blood sugar",
            "B. glycogen",
            "C. bile",
            "D. urea",
            "D. urea", "D")),


        Questions( objective = Objective( "17", "", "", "",
            "Which of the following glands also serves as an exocrine gland?",
            "A. Ovary",
            "B. Pancreas",
            "C. Adrenal",
            "D. Thyroid",
            "B. Pancreas", "B")),

        Questions( objective = Objective( "18", "", "", "",
            "Which of the following sequences is the correct route of the transmission of impulses along a reflex arc?",
            "A. Receptor→sensoryneuron→synapse→intermediateneuron→synapse→motorneuron→effector",
            "B. Receptor→motorneuron→synapse→intermediateneuron→synapse→sensoryneuron→effector",
            "C. Effector→intermediateneuron→synapse→motorneuron→synapse→sensoryneuron→receptor",
            "D. Effector→motorneuron→synapse→sensoryneuron→synapse→intermediateneuron→receptor",
            "A. Receptor→sensoryneuron→synapse→intermediateneuron→synapse→motorneuron→effector",
            "A"
        )),

        Questions( objective = Objective( "19", "", "", "",
            "When viewing an object that is close to the human eye, the",
            "A. eye lens becomes thin",
            "B. ciliary muscles relax",
            "C. suspensory lens become taut",
            "D. eye lens becomes fat",
            " D. eye lens becomes fat",
            "D"
        )),


        Questions( objective = Objective( "20", "", "", "",
            "The diagram above is an illustration of the human sperm. The part labelled I is the",
            "A. acrosome",
            "B. nucleus",
            "C. mitochondrion",
            "D. tail",
            "A. acrosome", "A")),

        Questions( objective = Objective( "21", "", "", "",
            "In the diagram of the human sperm above, the function of the part labelled II is to ",
            "A. fuse the ovum during fertilization",
            "B. generate the energy for the sperm to swim to the fallopian tube",
            "C. help the sperm to swim forward",
            "D. dissolve the membrane of the egg during fertilization",
            "C. help the sperm to swim forward", "C")),

                    Questions( objective = Objective( "22", "", "", "",
                "Which of the following types of placentation is not common amongst syncarpous pistils?",
                "A. Marginal",
                "B. Axile",
                "C. Parietal",
                "D. Free central",
                "A. Marginal", "A")),

            Questions( objective = Objective( "23", "", "", "",
                "The complex energy-rich organic matter which living organisms need for life is",
                "A. water",
                "B. air",
                "C. food",
                "D. mineral salts",
                "C. food", "C")),


            Questions( objective = Objective( "24", "", "", "",
                "Which of the following processes are associated with photosynthesis? I. Energy from sunlight is absorbed   II. Carbon dioxide is evolved   III. Oxygen is given off   IV. Glucose is synthesized",
                "A. I and II only",
                "B. I, II and IV only",
                "C. I, III and IV only",
                "D. I, II, III and IV",
                "C. I, III and IV only", "C")),

            Questions( objective = Objective( "25", "", "", "",
                "Which of the following function is associated with calcium in plants? Formation of",
                "A. cell wall",
                "B. ribosomes",
                "C. proteins",
                "D. cell membrane",
                " A. cell wall", "A")),

            Questions( objective = Objective( "26", "", "", "",
                "The diagram above shows the dentition of an organism. What organism is this?",
                "A. rabbit",
                "B. cat",
                "C. frog",
                "D. man",
                "D. man", "D")),

            Questions( objective = Objective( "27", "", "", "",
                "The diagrams below show the dentition of an organism. The function of the teeth labelled X is for",
                "A. biting and grasping",
                "B. chewing and grinding",
                "C. tearing and grasping",
                "D. chewing and tearing",
                "C. tearing and grasping", "C")),

            Questions( objective = Objective( "28", "", "", "",
                "The teeth which are absent in the young of the organism whose dentition is shown above is labelled",
                "A. W",
                "B. X",
                "C. Y",
                "D. Z",
                "D. Z", "D")),

            Questions( objective = Objective( "29", "", "", "",
                "The number of individuals that the environment can support over a long period of time is its",
                "A. growth rate",
                "B. total capacity",
                "C. population capacity",
                "D. carrying capacity",
                " C. population capacity", "C")),


            Questions( objective = Objective( "3", "", "", "",
                "A good site for secondary succession would be",
                "A. a sand dune",
                "B. a bare rock",
                "C. a land that has just had forest fire",
                "D. a stretch of barren land",
                "C. a land that has just had forest fire", "C")),

            Questions( objective = Objective( "31", "", "", "",
                "A population which exceeds its carrying capacity and then collapses is represented graphically by a",
                "A. bell-shaped curve",
                "B. linear curve",
                "C. sigmoid curve",
                "D. skewed curve",
                "A. bell-shaped curve", "A")),

            Questions( objective = Objective( "32", "", "", "",
                "The natural dwelling place of an organism is called its",
                "A. ecological niche",
                "B. habitat",
                "C. population",
                "D. environment",
                "B. habitat", "B")),

            Questions( objective = Objective( "33", "", "", "",
                "Which of the following ecological factors will result in food shortage?",
                "A. Drought",
                "B. Low rate of reproduction",
                "C. Emigration",
                "D. Topography",
                "A. Drought", "A")),

            Questions( objective = Objective( "34", "", "", "",
                "Soil permeability refers to ",
                "A. how easily water passes through the soil",
                "B. the proportion of air in the soil",
                "C. the proportion of water the soil holds",
                "D. how well water rises up the soil",
                "A. how easily water passes through the soil", "A")),

            Questions( objective = Objective( "35", "", "", "",
                "Which of the following groups of organisms do not have members that can be called autotrophs?",
                "A. Protists",
                "B. Mosses",
                "C. Chlorophyta",
                "D. Fungi",
                " D. Fungi", "D")),

            Questions( objective = Objective( "36", "", "", "",
                "Which of the following pyramids gives the most accurate picture of the relationships between at the various trophic levels in a food chain? A pyramid of",
                "A. numbers",
                "B. energy",
                "C. biomass",
                "D. size",
                "B. energy", "B")),

            Questions( objective = Objective( "37", "", "", "",
                "Which of the following statements is not associated with pyramids of energy?",
                "A. Efficiency of energy transfer between trophic levels can be studied",
                "B. Comparisons of pyramids for different ecosystems can be made",
                "C. More accurate comparisons of trophic levels",
                "D. Representation of numbers of organisms at different trophic levels",
                " B. Comparisons of pyramids for different ecosystems can be made", "B")),

            Questions( objective = Objective( "38", "", "", "",
                "Which of the following materials is not easily biodegradable?",
                "A. Polythene bag",
                "B. Cotton bag",
                "C. Hides and Skin bag",
                "D. Paper bag",
                "A. Polythene bag", "A")),

            Questions( objective = Objective( "39", "", "", "",
                "Which of the following pairs of organisms is in a mutualistic relationship?",
                "A. Hydra and Sea anemone",
                "B. Hermit crab and Sea anemone",
                "C. Dodder plant and Cocoa plant",
                "D. Mistletoe and Kolanut",
                "B. Hermit crab and Sea anemone", "B")),

            Questions( objective = Objective( "40", "", "", "",
                "The establishment of game reserves and parks is a method of",
                "A. conserving natural resources",
                "B. cultivating game",
                "C. controlling pollution",
                "D. cultural awareness",
                " A. conserving natural resources", "A")),

            Questions( objective = Objective( "41", "", "", "",
                "Which of the following practices is not used in conserving water?",
                "A. Afforestation",
                "B. Damming",
                "C. Deforestation",
                "D. Reforestation",
                "C. Deforestation", "C")),

            Questions( objective = Objective( "42", "", "", "",
                "Which of the following resources cannot be renewed?",
                "A. Air",
                "B. Petroleum",
                "C. Food crop",
                "D. Soil",
                "B. Petroleum", "B")),

            Questions( objective = Objective( "43", "", "", "",
                "The type of variation illustrated above is",
                "A. continuous variation",
                "B. discontinuous variation",
                "C. morphological variation",
                "D. environmental variation",
                "B. discontinuous variation", "B")),

            Questions( objective = Objective( "44", "", "", "",
                "Which of the following characters is not a morphological variation?",
                "A. shape of the nose",
                "B. colour of skin",
                "C. colour of hair",
                "D. tongue rolling",
                " D. tongue rolling", "D")),


            Questions( objective = Objective( "45", "", "", "",
                "An apple plant can produce sexually and asexually and it has 40 chromosomes in its leaf cells. How many chromosomes would be in each gamete and somatic cell?",
                "A. 20 chromosomes in the gametes and 10 in the somatic cells",
                "B. 40 chromosomes in the gametes and 20 in the somatic cells",
                "C. 20 chromosomes in the gametes and 40 in the somatic cells",
                "D. 40 chromosomes in the gametes and 40 in the somatic cells",
            " C. 20 chromosomes in the gametes and 40 in the somatic cells", "C")),

        Questions( objective = Objective( "46", "", "", "",
            "Assuming that A is the gene for normal skin color and is dominant, while a is the gene for albinism and its recessive, what is the likely genotype of the couple which had 50% normal and 50% albino offspring?",
            "A. AA, aa",
            "B. Aa, aa",
            "C. AA, Aa",
            "D. Aa, Aa",
            "B. Aa, aa", "B")),

        Questions( objective = Objective( "47", "", "", "",
            "Which of the following statements is true about mutation?",
            "A. Phenotype is not involved",
            "B. Genotype is not involved",
            "C. Artificial induction is not possible",
            "D. Genotype is involved",
            " D. Genotype is involved", "D")),

        Questions( objective = Objective( "48", "", "", "",
            "One of the structural adaptations of mammals for movement on land is the development of the",
            "A. hollow bones",
            "B. pentadactyl limb",
            "C. fused thoracic bones",
            "D. streamlined body",
            "B. pentadactyl limb", "B")),

        Questions( objective = Objective( "49", "", "", "",
            "Which of the following is NOT characteristic of social insects?",

            "A. All members are identical",
            "B. There is division of labour",
            "C. The members dwell in the same habitat",
            "D. Some members protect the queen",
            " A. All members are identical", "A")),

        Questions( objective = Objective( "50", "", "", "",
            "The gradual cumulative, adaptive and heritable changes in an organism over a long period of time resulting in new species is called",
            "A. adaptation",
            "B. survival",
            "C. organic evolution",
            "D. interspecific competition",
            "C. organic evolution", "C")),

        )

}
