package com.pktech.data.repository.maths

import com.pktech.domain.model.Objective
import com.pktech.domain.model.Questions

class MathsRepoDB {

    private val maths2012DB = listOf<Questions>(

        Questions( objective = Objective( "1", "", "", "",
            "Express 302.10495 correct to five significant figures",
            "A. 302.10",
            "B. 302.11",
            "C. 302.105",
            "D. 302.1049",
            "A. 302.10")
        ),

        Questions( objective = Objective( "2", "", "", "",
            "Simplify; 35√×46√22√×32√",
            "A. 2–√",
            "B. 5–√",
            "C. 22–√",
            "D. 2√5",
            "D. 2√5")),

        Questions( objective = Objective( "3", "", "", "",
            "In 1995, the enrollment of two schools X and Y were 1,050 and 1,190 respectively. Find the ration of the enrollments of X and Y",
            "A. 50:11",
            "B. 15:17",
            "C. 13:55",
            "D. 12:11",
            "B. 15:17")),

        Questions( objective = Objective( "4", "", "", "",
            "Convert 3510 to number in base 2",
            "A. 1011",
            "B. 10011",
            "C. 100011",
            "D. 11001",
            "C. 100011")),

        Questions( objective = Objective( "5", "", "", "",
            "The nth term of a sequence is Tn = 5 + (n - 1)2. Evaluate T4 - T6",
            "A. 30",
            "B. 16",
            "C. -16",
            "D. -30",
            "C. -16")),

        Questions( objective = Objective( "6", "", "", "",
            "Mr. Manu travelled from Accra to Pamfokromb a distance of 720km in 8 hours. What will be his speed in m/s?",
            "A. 25m/s",
            "B. 150m/s",
            "C. 250m/s",
            "D. 500m/s",
            "A. 25m/s")),

        Questions( objective = Objective( "7", "", "", "",
            "If N2,500.00 amounted to N3,50.00 in 4 years at simple interest, find the rate at which the interest was charged",
            "A. 5%",
            "B. 712%",
            "C. 8%",
            "D. 10%",
            "D. 10%")),

        Questions( objective = Objective( "8", "", "", "",
            "Solve for x in the equation; 1x+23x=13",
            "A. 5",
            "B. 4",
            "C. 3",
            "D. 1",
            "A. 5")),

        Questions( objective = Objective( "9", "", "", "",
            "Simplify: 54k2−63k+1",
            "A. 6(1 - 3k2)",
            "B. 6(3k2 - 1)",
            "C. 6(3k - 1)",
            "D. 6(1 - 3k)",
            "C. 6(3k - 1)")),

        Questions( objective = Objective( "10", "", "", "",
            "Represent in inequality -7 < 4x + 9 <_13 on a number line DIAGRAMS",
            "A",
            " B",
            "C",
            " D",
            "")),

        Questions( objective = Objective( "11", "", "", "",
            "Make p the subject of the relation: q = 3pr+s2",
            "A. p = 2q−rs6",
            "B. p = 2qr - sr - 3",
            "C. p = 2qr−s6",
            "D. p = (2qr−rs)/6",
            "D. p = (2qr−rs)/6")),

        Questions( objective = Objective( "12", "", "", "",
            "If x + y = 2y - x + 1 = 5, find the value of x",
            "A. 3",
            "B. 2",
            "C. 1",
            "D. -1",
            " A. 3")),

        Questions( objective = Objective( "13", "", "", "",
            "The sum of 12 and one third of n is 1 more than twice n. Express the statement in the form of an equation",
            "A. 12n - 6 = 0",
            "B. 3n - 12 = 0",
            "C. 2n - 35 = 0",
            "D. 5n - 33 = 0",
            "D. 5n - 33 = 0")),

        Questions( objective = Objective( "14", "", "", "",
            "Solve the inequality: −m2−54≥5m12−76",
            "A. m ≤54",
            "B. m ≥54",
            "C. m ≤−1/11",
            "D. m ≥−1/11",
            "D. m ≥−1/11")),

        Questions( objective = Objective( "15", "", "", "",
            "The curved surface area of a cylindrical tin is 704cm2. If the radius of its base is 8cm, find the height. [Take π=227]",
            "A. 14cm",
            "B. 9cm",
            "C. 8cm",
            "D. 7cm",
            "A. 14cm")),

        Questions( objective = Objective( "16", "", "", "",
            "The lengths of the minor and major arcs 54cm and 126cm respectively. Calculate the angle of the major sector",
            "A. 360o",
            "B. 252o",
            "C. 246o",
            "D. 234o",
            "B. 252o")),

        Questions( objective = Objective( "17", "", "", "",
            "A sector of a circle which subtends 172o at the centre of the circle ha a perimeter of 600cm. Find, correct to the nearest cm, the radius of the circle. (π =22/7)",
            "A. 120cm",
            "B. 116cm",
            "C. 107cm",
            "D. 100cm",
            "A. 120cm")),

        Questions( objective = Objective( "18", "", "", "",
            "In the diagram, |QR| = 10m, |SR| = 8m  < QPS = 30o, < QRP = 90o and |PS| = x, Find x",
        "A. 1.32m",
        "B. 6.32m",
        "C. 9.32m",
        "D. 17.32",
        "C. 9.32m")),


    Questions( objective = Objective( "19", "", "", "",
    "In △ XYZ, /XY/ = 8cm, /YZ/ = 10cm and /XZ/ = 6cm. Which of these relation is true?",
    "A. /XY/ + /YZ/ = /XZ/",
    "B. /XY/ - /YZ/ = /XZ/",
    "C. /XY/2 = /Y/2 - /XY/2",
    "D. /YZ/2 = /XZ/2 + /XY/2",
    "")),

    Questions( objective = Objective( "20", "", "", "",
    "In the diagram, O is a circle centre of the circle PQRS and < PSR = 86o. If < PQR = xo, find x",
    "A. 108o",
    "B. 172o",
    "C. 130o",
    "D. 50o",
    "B. 172o")),

    Questions( objective = Objective( "21", "", "", "",
    "The diagram is a circle centre O. If < SPR = 2m and < SQR = n, express m in terms of n",
    "A. m = n/2",
    "B. m = 2n",
    "C. m = n - 2",
    "D. m = n + 2",
    "A. m = n/2")),

    Questions( objective = Objective( "22", "", "", "",
    "In the diagram, MQ//RS, < TUV = 70o and < RLV = 30o. Find the value of x",
    "A. 150o",
    "B. 110o",
    "C. 100o",
    "D. 95o",
    "C. 100o")),

    Questions( objective = Objective( "23", "", "", "",
    """
        Is the diagram, MN, PQ and RS are three intersecting straight lines. Which of the following statements is/are true?
    i. t = y
    ii. x + y + z + m = 180o
    ii. x + m + n = 180o
    iv. x + n = m + z
    """.trimIndent() ,
    "A. i and iv",
    "B. ii",
    "C. iii",
    "D. iv",
    "C. iii")),

    Questions( objective = Objective( "24", "", "", "",
    "If cos(x + 40)o = 0.0872, what is the value of x?",
    "A. 85o",
    "B. 75o",
    "C. 65o",
    "D. 45o",
    " D. 45o")),

    Questions( objective = Objective( "25", "", "", "",
    "A kite flies on a taut string of length 50m inclined at tan angle 54o to the horizontal ground. The height of the kite above the ground is",
    "A. 50 tan 30o",
    "B. 50 sin 54o",
    "C. 50 tan 54o",
    "D. 50 sin 36o",
    "B. 50 sin 54o")),

    Questions( objective = Objective( "26", "", "", "",
    "The position of three ships P,Q and R at sea are illustrated in the diagram. The arrows indicated the North direction. The bearing of Q from P is 050o and < PQR = 72o. Calculate the bearing of R and Q",
    "A. 155o",
    "B. 80o",
    "C. 158o",
    "D. 91o",
    "C. 158o")),

    Questions( objective = Objective( "27", "", "", "",
    "Given that the mean of the scores 15, 21, 17, 26, 18 and 29 is 21, calculate the standard deviation of the scores",
    "A.√10",
    "B. 4",
    "C. 5",
    "D. √30",
    "C. 5")),


    Questions( objective = Objective( "28", "", "", "",
    "A bag contains 4 red and 6 black balls of the same size. If the balls are shuffled briskly and two balls are drawn one after the other without replacement, find the probability of picking balls of different colours",
    "A. 8/15",
    "B. 13/25",
    "C. 11/15",
    "D. 13/15",
    "A. 8/15")),

    Questions( objective = Objective( "29", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. How many students are in the class?",
    "A. 10",
    "B. 24",
    "C. 25",
    "D. 30",
    "C. 25")),


    Questions( objective = Objective( "30", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. Calculate the mean of the distribution.",
    "A. 6.0",
    "B. 3.0",
    "C. 2.4",
    "D. 1.8",
    "C. 2.4")),


    Questions( objective = Objective( "31", "", "", "",
    "The bar chart shows the frequency distribution of marks scored by students in a class test. What is the median of the distribution?",
    "A. 2",
    "B. 4",
    "C. 6",
    "D. 8",
    "A. 2")),

    Questions( objective = Objective( "32", "", "", "",
    "Which of these statements about y =√ 8m  is correct?",
    "A. log y = log 8 x log √m",
    "B. log y = 3 log 2 x 1/2 log m",
    "C. log y = 3 log 2 - 1/2 log m",
    "D. log y = 3 log 2 + 1/2 log m",
    ""
    )),

    Questions( objective = Objective( "33", "", "", "",
    "If x + 0.4y = 3 and y = 12x, find the value of (x + y)",
    "A. 114",
    "B. 212",
    "C. 3 ¾",
    "D. 5",
    "C. 3 ¾")),

    Questions( objective = Objective( "34", "", "", "",
    "Express 3 - [x−y/y] as a single fraction",
    "A. 3xyy",
    "B. x−4yy",
    "C. 4y−x/y",
    "D. 3 - x−yy",
    "C. 4y−x/y")),

    Questions( objective = Objective( "35", "", "", "",
    "Find the coefficient of m in the expression of (m2−112) (m + 23)",
    "A. -16",
    "B. - 12",
    "C. -1",
    "D. -116",
    "D. -116")),

    Questions( objective = Objective( "36", "", "", "",
    "In the diagram, MN//PO, < PMN = 112o, < PNO = 129oo and < MPN = yo. Find the value of y",
    "A. 51o",
    "B. 54o",
    "C. 56o",
    "D. 68o",
    "B. 54o")),

    Questions( objective = Objective( "37", "", "", "",
    "If p = {prime factors of 210} and Q = {prime less than 10}, find p ∩ Q",
    "A. {1,2, 3}",
    "B. {2, 3, 5}",
    "C. {1, 3, 5,7}",
    "D. {2,3,5,7}",
    "D. {2,3,5,7}")),


    Questions( objective = Objective( "38", "", "", "",
    "Alfred spent 14 of his money on food, 13 on clothing and save the rest. If he saved N72,20.00, how much did he spend on food?",
    "A. N43,200.00",
    "B. N43,000.00",
    "C. N42,200.00",
    "D. N40,000.00",
    "A. N43,200.00")),


    Questions( objective = Objective( "39", "", "", "",
    "Solve (27125)-13 x (49)12",
    "A. 10/9",
    "B. 9/10",
    "C. ⅖",
    "D. 12/15",
    "A. 10/9")),


    Questions( objective = Objective( "40", "", "", "",
    "The sum of the interior angles of regular polygon is 1800o. How many sides has the polygon?",
    "A. 16",
    "B. 12",
    "C. 10",
    "D. 8",
    "B. 12")),

    Questions( objective = Objective( "41", "", "", "",
    "The diagram is a circle with centre O. PRST are points on the circle. Find the value of < PRS",
    "A. 144o",
    "B. 72o",
    "C. 40o",
    "D. 36o",
    "D. 36o")),

    Questions( objective = Objective( "42", "", "", "",
    "The diagram is a circle of radius |QR| = 4cm. R¯ is a tangent to the circle at R. If TPO = 120o, find |PQ|.",
    "A. 2.32cm",
    "B. 1.84cm",
    "C. 0.62cm",
    "D. 0.26cm",
    "C. 0.62cm")),

    Questions( objective = Objective( "43", "", "", "",
    "If x and y are variables and k is a constant, which of the following describes an inverse relationship between x and y?",
    "A. y = kx",
    "B. y = kx",
    "C. y = k√x",
    "D. y = x + k",
    "",
    )),

    Questions( objective = Objective( "44", "", "", "",
    "In the diagram, |SR| = |QR|. < SRP = 65o and < RPQ = 48o, find < PRQ",
    "A. 65o",
    "B. 45o",
    "C. 25o",
    "D. 19o",
    "D. 19o")),

    Questions( objective = Objective( "45", "", "", "",
    "The graph is that of y = 2x2 - 5x - 3. For what value of x will y be negative? For what value of x will y be negative?",
    "A. -1/2≤x < 3",
    "B. -1/2<x≤3",
    "C. -1/2<x<3",
    "D. -1/2≤x≤3",
    "C. -1/2<x<3")),

    Questions( objective = Objective( "46", "", "", "",
    "The graph is that of y = 2x2 - 5x - 3. For what value of x will y be negative? What is the gradient of y = 2x2 - 5x - 3 at the point x = 4?",
    "A. 11.1",
    "B. 10.5",
    "C. 10.3",
    "D. 9.9",
    "A. 11.1")),
    Questions( objective = Objective( "47", "", "", "",
    "The diagram is a polygon. Find the largest of its interior angles",
    "A. 300o",
    "B. 100o",
    "C. 120o",
    "D. 150o",
    " D. 150o")),

    Questions( objective = Objective( "48", "", "", "",
    "The volume of a cuboid is 54cm3. If the length, width and height of the cuboid are in the ratio 2:1:1 respectively, find its total surface area",
    "A. 108cm2",
    "B. 90cm2",
    "C. 80cm2",
    "D. 72cm2",
    "B. 90cm2")),

    Questions( objective = Objective( "49", "", "", "",
    "A side and a diagonal of a rhombus are 10cm and 12cm respectively, Find its area",
    "A. 20cm2",
    "B. 24cm2",
    "C. 48cm2",
    "D. 96cm2",
    "D. 96cm2")),


    Questions( objective = Objective( "50", "", "", "",
    "Factorise completely: 32x2y - 48x3y3",
    "A. 16x2y(2 - 3xy2)",
    "B. 8xy(4x - 6x2y2)",
    "C. 8x2y(4 - 6xy2)",
    "D. 16xy(2x - 3x2y2)",
    "A. 16x2y(2 - 3xy2)")),

    )

    val mathYear = listOf<List<Questions>>(
        maths2012DB
    )
}