package com.example.repository.economics

import com.example.repository.Objective
import com.example.repository.Questions

class Economics2012Repo {

    val economics2012 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "Which of the following problems arises where there are more than one technically possible methods of production? ",
            "A. Where to produce ",
            "B. For whom to produce ",
            "C. How to produce ",
            "D. What to produce",
            "C. How to produce ", "C")
        ),


        Questions( objective = Objective( "2", "", "", "",
            "Visible balance is also known as",
            "A. terms of trade. ",
            "B. balance of payments",
            "C. balance of trade.",
            "D. capital balance. ",
            "C. balance of trade.", "C")),

        Questions( objective = Objective( "3", "", "", "",
            "A shift in the demand curve indicates",
            "A. exceptional demand. ",
            "B. change in demand. ",
            "C. change in quantity demanded. ",
            "D. elasticity of demand. ",
            "B. change in demand. ", "B")),

        Questions( objective = Objective( "4", "", "", "",
            "If a 6% decrease in price results in more than 6% decrease in quantity supplied, supply can be regarded as",
            "A. elastic.",
            "B. unitary elastic. ",
            "C. perfectly inelastic. ",
            "D. perfectly elastic.",
            "A. elastic.", "A")),

        Questions( objective = Objective( "5", "", "", "",
            "A condition for consumer utility maximization is ",
            "A. equality of the ratio of marginal utilities and the ratio of prices.",
            "B. equality of the ratio of average utilities and the ratio of prices.",
            "C. equality of the marginal utility to total utility ratio for both commodities.",
            "D. total utility and marginal utility must be zero.",
            "A. equality of the ratio of marginal utilities and the ratio of prices.", "A")),

        Questions( objective = Objective( "6", "", "", "",
            "Which of the following best describes the mode? The ",
            "A. observation with the highest frequency ",
            "B. average of two middle numbers",
            "C. item that occupies the middle position",
            "D. difference of two extreme values ",
            "A. observation with the highest frequency ", "A")),

        Questions( objective = Objective( "7", "", "", "",
            "Where a commodity takes an insignificant proportion of the consumer's income, demand for it will be ",
            "A. unitary elastic.",
            "B. price inelastic.",
            "C. fairly elastic.",
            "D. income inelastic.",
            "B. price inelastic.", "B")),

        Questions( objective = Objective( "8", "", "", "",
            "A demand schedule shows the quantities of goods that are",
            "A. bought at given prices at a time. ",
            "B. supplied at given prices at a time. ",
            "C. produced at given prices at a time.",
            "D. reserved for future consumption.",
            "A. bought at given prices at a time.", "A")),

        Questions( objective = Objective( "9", "", "", "",
            "The demand curve for a commodity is downward sloping because the consumer will pay",
            "A. less as the marginal utility falls. ",
            "B. more as the marginal utility falls. ",
            "C. less as the total utility falls.",
            "D. more as the average utility falls.",
            "C. less as the total utility falls.", "C")),

        Questions( objective = Objective( "10", "", "", "",
            "A decrease in the demand for a product X resulted in a decrease in the demand for another product Y. The demand for X and Y is",
            "A. derived.",
            "B. composite. ",
            "C. joint. ",
            "D. competitive.",
            "C. joint. ", "C")),

        Questions( objective = Objective( "11", "", "", "",
            "Any price below the equilibrium price will lead to",
            "A. increase in supply. ",
            "B. excess demand. ",
            "C. equality of demand and supply.",
            "D. decrease in demand.",
            "B. excess demand.", "B")),

        Questions( objective = Objective( "12", "", "", "",
            "The allocation of goods and services in a free market economy is performed by ",
            "A. the price system. ",
            "B. the banking system.",
            "C. the central planning body. ",
            "D. government budgets. ",
            "A. the price system.", "A")),

        Questions( objective = Objective( "13", "", "", "",
            "Given the demand function Qd = 20 - P. What is Qd when P is $12?",
            "A. 6 units",
            "B. 10 units",
            "C. 12 units",
            "D. 14 units",
            "D. 14 units", "D")),

        Questions( objective = Objective( "14", "", "", "",
            "If a particular consumer derives total utility of 22 utils having consumed 4 units of a given product, his average utility will be ",
            "A. 88 utils.",
            "B. 18 utils.",
            "C. 5.5 utils.",
            "D. 3.5 utils.",
            "C. 5.5 utils.", "C")),


        Questions( objective = Objective( "15", "", "", "",
            "The law of diminishing marginal utility applies to a",
            "A. firm which minimizes cost.",
            "B. consumer who maximizes satisfaction.",
            "C. producer who maximizes marginal product.",
            "D. consumer who minimizes total utility.",
            "B. consumer who maximizes satisfaction.", "B")),

        Questions( objective = Objective( "16", "", "", "",
            "Why is the law of diminishing returns a short run phenomenon? ",
            "A. All inputs are fixed",
            "B. All inputs are variable ",
            "C. Some outputs are variable ",
            "D. Some inputs are variable ",
            "A. All inputs are fixed ", "A")),

        Questions( objective = Objective( "17", "", "", "",
            "Which of the following is capable of increasing the population of a country? ",
            "A. Decrease in death rate ",
            "B. Increase in death rate ",
            "C. Poor medical facilities ",
            "D. Decrease in birth rate ",
            "A. Decrease in death rate ", "A")),

        Questions( objective = Objective( "18", "", "", "",
            "In the firm's production process, marginal cost",
            "A. falls continuously throughout.",
            "B. falls and later rises.",
            "C. remains unchanged throughout. ",
            "D. rises and later falls.",
            "B. falls and later rises. ", "B")),

        Questions( objective = Objective( "19", "", "", "",
            "If a firm's price is less than average cost but more than average variable cost, the firm is covering",
            "A. all of its fixed cost and variable cost. ",
            "B. all of its fixed cost and part of variable cost.",
            "C. all of its variable cost and part of fixed cost.",
            "D. part of its fixed cost and part of variable cost.",
            "A. all of its fixed cost and variable cost.", "A")),

        Questions( objective = Objective( "20", "", "", "",
            "An arrangement in which the debts of a company can only be paid from its own assets implies",
            "A. unlimited liability.",
            "B. transferred liability.",
            "C. limited liability.",
            "D. capital liability. ",
            "C. limited liability.", "C")),

        Questions( objective = Objective( "21", "", "", "",
            "One reason why small scale businesses are very common in West Africa is that",
            "A. they can easily float shares.",
            "B. their management boards are easily formed.",
            "C. their initial capital is easy to raise.",
            "D. their dividend payments are very regular.",
            "C. their initial capital is easy to raise.", "C")),

        Questions( objective = Objective( "22", "", "", "",
            "A public limited company could finance its operations through",
            "A. government taxes.",
            "B. equity shares.",
            "C. dividend payments.",
            "D. import duties.",
            "B. equity shares. ", "B")),

        Questions( objective = Objective( "23", "", "", "",
            "The factor of production which takes the initiative in combining resources for production is known as ",
            "A. capital.",
            "B. land.",
            "C. entrepreneur. ",
            "D. labour.", "C. entrepreneur. ", "C")),

        Questions( objective = Objective( "24", "", "", "",
            "The type of monopoly that develops as a result of granting patent right is known as",
            "A. natural monopoly. ",
            "B. state monopoly ",
            "C. legal monopoly.",
            "D. discriminating monopoly.",
            "C. legal monopoly. ", "C")),

        Questions( objective = Objective( "25", "", "", "",
            "Which of the following markets determines its own price or output? ",
            "A. Perfect market ",
            "B. Common market",
            "C. Monopoly market ",
            "D. Commodity market",
            "C. Monopoly market ", "C")),

        Questions( objective = Objective( "26", "", "", "",
            "Which of the following is a function of a retailer? ",
            "A. Banking services",
            "B. Hoarding services",
            "C. Storage services ",
            "D. Sales services",
            "D. Sales services ", "C")),

        Questions( objective = Objective( "27", "", "", "",
            "The difference between the number of immigrants and emigrants is",
            "A. natural growth rate.",
            "B. natural increase.",
            "C. net migration.",
            "D. census.",
            "C. net migration.", "C")),

        Questions( objective = Objective( "28", "", "", "",
            "All the following are features of optimum population except ",
            "A. full employment of available resources.",
            "B. unlimited amount of unexploited resources.",
            "C. maximum per capita production and income.",
            "D. high standard of living.",
            "B. unlimited amount of unexploited resources.", "B")),

        Questions( objective = Objective( "29", "", "", "",
            "The financial institution that specializes in risk spreading is called",
            "A. an investment bank.",
            "B. a development bank.",
            "C. an insurance company.",
            "D. the stock exchange.",
            "C. an insurance company.", "C")),

        Questions( objective = Objective( "30", "", "", "",
            "The following are means of reducing the population of a country except encouraging",
            "A. emigration.",
            "B. family planning.",
            "C. early marriage.",
            "D. sex education.",
            "C. early marriage.", "C")),

        Questions( objective = Objective( "31", "", "", "",
            "Which of the following features best describes peasant agriculture in West Africa'? It",
            "A. specializes in the production of one crop.",
            "B. involves the use of small farm holdings.",
            "C. is a capital-intensive system of farming.",
            "D. is mostly associated with tree crops.",
            "A. specializes in the production of one crop.", "A")),

        Questions( objective = Objective( "32", "", "", "",
            "One of the problems facing industrial development in West African countries is",
            "A. inadequate large market.",
            "B. inadequate infrastructure.",
            "C. inadequate supply of labour.",
            "D. unavailability of natural resources.",
            "B. inadequate infrastructure.", "B")),

        Questions( objective = Objective( "33", "", "", "",
            "In a situation where the finished product of an industry is fragile, bulky and perishable, such an industry should be located close to its ",
            "A. raw materials.",
            "B. market.",
            "C. labour supply.",
            "D. power supply.",
            "B. market. ", "B")),

        Questions( objective = Objective( "34", "", "", "",
            "If Y Income, C = Consumption, I = Investment, X = Export and M = Import, then national income is",
            "A. Y=C-I + (x + m). ",
            "B. Y=C+I+ (x + m).",
            "C. Y=C+I+ (x-m).",
            "D. Y=C+I+(m-x).",
            "C. Y=C+I+ (x-m).", "C")),

        Questions( objective = Objective( "35", "", "", "",
            "The national income is the ",
            "A. Gross Domestic Product at market prices. ",
            "B. Gross National Product at factor cost.",
            "C. Net National Product at factor cost.",
            "D. Net National Product at market prices.",
            "A. Gross Domestic Product at market prices. ", "A")),

        Questions( objective = Objective( "36", "", "", "",
            "When depreciation is deducted from Gross National Product, the result is ",
            "A. total national income.",
            "B. gross domestic product.",
            "C. net national product.",
            "D. net domestic product.",
            "A. total national income.", "A")),

                Questions( objective = Objective( "37", "", "", "",
            "Mr. Okpoti has meat and wants maize, while Mr. Adama has maize and wants meat.",
            "A transaction possible because of",
            "A. joint demand.",
            "B. scale of preference.",
            "C. double coincidence of wants.",
            "D. opportunity cost.",
            "C. double coincidence of wants.", "C")),

        Questions( objective = Objective( "38", "", "", "",
            "Which of the following is not a form of money? ",
            "A. Coins",
            "B. Bank notes ",
            "C. Bank balance ",
            "D. Bank deposit ",
            "C. Bank balance ", "C")),

        Questions( objective = Objective( "39", "", "", "",
            "A price index as a statistic, measures",
            "A. how the value of money changes over time.",
            "B. the volume of currency in the economy.",
            "C. the exchange rate of a country's currency. ",
            "D. the composition of goods and services.",
            "C. the exchange rate of a country's currency. ", "C")),

        Questions( objective = Objective( "40", "", "", "",
            "The difference between birth rate and death rate is known as",
            "A. demographic transition.",
            "B. natural growth rate.",
            "C. migration rate.",
            "D. fertility rate.",
            "B. natural growth rate.", "B")),

        Questions( objective = Objective( "41", "", "", "",
            "In open market operations, what the Central Bank sells or buys are",
            "A. shares.",
            "B. debentures. ",
            "C. securities.",
            "D. equities.",
            "C. securities.", "C")),

        Questions( objective = Objective( "42", "", "", "",
            "The following are reasons for the failure of agricultural policies in West Africa except",
            "A. vague policy statements.",
            "B. negation of policies.",
            "C. creation of agro-service stations",
            "D. provision of obsolete implements.",
            "C. creation of agro-service stations.", "C")),

        Questions( objective = Objective( "43", "", "", "",
            "A situation in which the estimated government revenue is less than the proposed expenditure for a given year can be described as",
            "A. surplus budgeting ",
            "B. supplementary budgeting",
            "C. balanced budgeting.",
            "D. deficit budgeting.",
            "D. deficit budgeting.", "D")),

                Questions( objective = Objective( "44", "", "", "",
            "An excise tax is imposed on goods",
            "A. smuggled into the country. ",
            "B. manufactured locally.",
            "C. imported into the country",
            "D. seized by Customs officials.",
            "B. manufactured locally", "B")),

        Questions( objective = Objective( "45", "", "", "",
            "Which of the following will not retard economic development in West Africa?",
            "A. Dependence on imports",
            "B. Population control ",
            "C. High level of illiteracy ",
            "D. Low level of savings",
            "B. Population control ", "B")),

        Questions( objective = Objective( "46", "", "", "",
            "When there is improvement in a country's terms of trade, it means that the country's",
            "A. exports are cheaper relative to imports.",
            " B. imports are cheaper relative to exports.",
            "C. volume of imports has declined.",
            "D. volume of exports has declined.",
            "C. volume of imports has declined.", "C")),

        Questions( objective = Objective( "47", "", "", "",
            "Which of the following is true about import substitution? It",
            "A. helps in increasing exportation.",
            "B. is meant to reduce exportation.",
            "C. enables a country to curtail importation.",
            "D. enables a country to improve on importation.",
            "C. enables a country to curtail importation.","c")),

        Questions( objective = Objective( "48", "", "", "",
            "Balance of payments problem can be corrected through",
            "A. increasing foreign reserves.",
            "B. increasing domestic borrowing.",
            "C. import promotion strategies.",
            "D. export promotion strategies.",
            "D. export promotion strategies.", "D")),

        Questions( objective = Objective( "49", "", "", "",
            "One of the reasons why government may erect a trade barrier is to",
            "A. control foreign currencies.",
            "B. protect infant industries.",
            "C. promote importation.",
            "D. diversify the economy.",
            "B. protect infant industries.", "B")),

        Questions( objective = Objective( "50", "", "", "",
            "Which of the following is not a function of the West African Development Bank?",
            "A. Promotion of both private and public investments in member states",
            "B. Financing and executing projects in member states",
            "C. Promotion of social development of member states",
            "D. Harmonization of oil prices to the advantage of member states",
            "B. Financing and executing projects in member states", "B")),
    )
}