package com.example.repository.government

import com.example.repository.Objective
import com.example.repository.Questions

class Government2013Repo {

    val government2013 = listOf<Questions>(
        Questions( objective =Objective("1", "", "", "",
            "Government can be defined as the study of",
            "A. constitutions",
            "B. cabinet system of government only",
            "C. how people rule themselves",
            "D. presidential system of government only",
            "C. how people rule themselves", "C",
        )
    ),

        Questions( objective =Objective("2", "", "", "",
    "which of the following is not an acceptable function of government?",
    "A. Defense",
    "B. supervision",
    "C. embarking on public enlightenment",
    "D. providing social amenities",
    "B. supervision",
    "B",
    )),

                Questions( objective =Objective("3", "", "", "",
    "Which of the following is a feature of a state?",
    "A. Pursuance of sectional interest",
    "B. Colonial expericnce",
    "C. Territorial boundary",
    "D. Temporary existence",
    "C. Territorial boundary",
    "C",
    )),


        Questions( objective =Objective("4", "", "", "",
    "As a political ideology, communism seeks to",
    "A. accumulate capital in the hands of a few",
    "B. accommodate division of citizens into classes",
    "C. eliminate all forms of socio-economic inequalities",
    "D. create economic opportunities for profit making",
    "C. eliminate all forms of socio-economic inequalities",
    "C",
    )),

        Questions( objective =Objective("5", "", "", "",
    "Totalitarianism means a government headed by",
    "A. a dictator",
    "B. wealthy people",
    "C. educated elite",
    "D. the masses",
    "A. a dictator",
    "A",
    )),


        Questions( objective =Objective("6", "", "", "",
    "Monarchy means government",
    "A. headed by a king",
    "B. by the people",
    "C. of the majority",
    "D. run by the elite",
    "A. headed by a king",
    "A",
    )),

        Questions( objective =Objective("7", "", "", "",
    "The rule of law is observed when",
    "A. democracy is practised",
    "B. laws are kept secret",
    "C. revolution is encouraged",
    "D. only the elite can govern",
    "A. democracy is practised",
    "A",
    )),

        Questions( objective =Objective("8", "", "", "",
    "Delegated legislation is necessary because it",
    "A. helps to promote dictatorship",
    "B. prevents even development",
    "C. is useful in times of emergency",
    "D. gives a lot of power to the president",
    "C. is useful in times of emergency",
    "C",
    )),

        Questions( objective =Objective("9", "", "", "",
    "One of the criticisms against delegated legislation is that it",
    "A. promotes separation of powers",
    "B. is not practiced in advanced countries",
    "C. encroaches on parliamentary power",
    "D. gives too much power to the judiciary",
    "C. encroaches on parliamentary power",
    "C",
    )),

        Questions( objective =Objective("10", "", "", "",
    "Fundamental Human Rights seek to",
    "A. promote the dignity of man",
    "B. train political activists",
    "C. encourages economic activities",
    "D. enthrone mob rule",
    "A. promote the dignity of man",
    "A",
    )),

        Questions( objective =Objective("11", "", "", "",
    "Constitutionalism implies that",
    "A. citizens should read the constitution always",
    "B. leaders should ignore the dictates of the constitution",
    "C. citizens should challenge the provisions of the constitution",
    "D. leaders should act according to the stipulations of the constitution",
    "D. leaders should act according to the stipulations of the constitution",
    "C",
    )),

        Questions( objective =Objective("12", "", "", "",
    "Which of the following is not a source of a country's constitution?",
    "A. Legislative decisions",
    "B. past constitutions",
    "C. writ of Mandamus",
    "D. Judicial precedents",
    "C. writ of Mandamus",
    "C"
    )),

        Questions( objective =Objective("13", "", "", "",
    "which of the following is not within the scope of a constitution?",
    "A. Fundamental Human Rights",
    "B. Organs of government",
    "C. Coup d'etat",
    "D. Preamble",
    "C. Coup d'etat",
    "C"
    )),

        Questions( objective =Objective("14", "", "", "",
    "Centralization of power is a feature of a",
    "A. federal system",
    "B. unitary system",
    "C. confederal system",
    "D. presidential system",
    "B. unitary system",
    "B",
    )),

        Questions( objective =Objective("15", "", "", "",
    "In a unitary state, governmental powers are concentrated at the",
    "A. component units",
    "B. local level",
    "C. centre",
    "D. regions",
    "C. centre",
    "C",
    )),

        Questions( objective =Objective("16", "", "", "",
    "Which of the following is true of a parliamentary system of government?",
    "A. there is an Executive President",
    "B. Fusion of powers is discouraged",
    "C. Collective responsibility is emphasized",
    "D. The Prime Minister is the head of the judiciary",
    "C. Collective responsibility is emphasized",
    "C",
    )),

        Questions( objective =Objective("17", "", "", "",
    "The system of government in which the president acts as the head of state and the head of government is",
    "A. diarchy",
    "B. Presidential",
    "C. unitary",
    "D. parliamentary",
    "B. Presidential",
    "B",
    )),

        Questions( objective = Objective("18", "", "", "",
    "Which of the following is a feature of a confederation?",
    "A. it has a rigid constitution",
    "B. the central government is stronger than the component units",
    "C. there is a legal right of secession",
    "D. there is no provision for a state constitution",
    "C. there is a legal right of secession",
    "C",
    )),


        Questions( objective =Objective("19", "", "", "",
    "Which of the following is a factor in the formation of a federation?",
    "A. Desire for a union",
    "B. Absence of a common enemy",
    "C. Small population",
    "D. Geographical incontiguity",
    "A. Desire for a union",
    "A",
    )),


        Questions( objective =Objective("20", "", "", "",
    "The formation and implementation of policies are the major duties of the",
    "A. police",
    "B. judiciary",
    "C. executive",
    "D. legislature",
    "C. executive",
    "C",
    )),

        Questions( objective =Objective("21", "", "", "",
    "Bicameralism is adopted because it",
    "A. guards against intra-party clashes",
    "B. prevents arbitrary law making",
    "C. projects party manifestos",
    "D. is the only system available",
    "B. prevents arbitrary law making",
    "B",
    )),


        Questions( objective =Objective("22", "", "", "",
    "Parliamentary filibuster refers to a",
    "A. a procedure of impeaching the president",
    "B. delay method of prolonging debates in parliament",
    "C. process of passing bills into law",
    "D. a special way of initiating money bills",
    "B. delay method of prolonging debates in parliament",
    "B",
    )),



        Questions( objective =Objective("23", "", "", "",
    "Which of the following functions is performed by the executive?",
    "A. Recruitment of judges",
    "B. Passing of bills to laws",
    "C. Adjudication of cases",
    "D. Implementation of policies",
    "D. Implementation of policies",
    "D",
    )),



        Questions( objective =Objective("24", "", "", "",
    "When a court of law declares an action of the executive ultra-vires , it implies that",
    "A. the action is illegal and above the power given",
    "B. the executive has to implement the action",
    "C. such an action should be passed into law",
    "D. only the legislature can deal with such an action",
    "A. the action is illegal and above the power given",
    "A",
    )),


        Questions( objective =Objective("25", "", "", "",
    "Which of the following is a duty of a good citizen?",
    "A. paying tax regularly",
    "B. Must assist the poor",
    "C. should challenge the of the land",
    "D. Must join the law enforcement agents",
    "A. paying tax regularly",
    "A",
    )),



        Questions( objective =Objective("26", "", "", "",
    "Citizens can be deprived of their rights during",
    "A. democratic regime",
    "B. parliamentary debate",
    "C. emergency periods",
    "D. political campaigns",
    "C. emergency periods",
    "C",
    )),

        Questions( objective =Objective("27", "", "", "",
    "Which of the following is an obligation of a citizen?",
    "A. Arresting offenders",
    "B. Voting at elections",
    "C. Prosecuting offenders",
    "D. Adjudicating cases",
    "B. Voting at elections",
    "B",
    )),

        Questions( objective =Objective("28", "", "", "",
    "A multi-party system often leads to the formation of a",
    "A. coalition government",
    "B. very strong executive",
    "C. dictatorial government",
    "D. confederal government",
    "A. coalition government",
    "C",
    )),


        Questions( objective =Objective("29", "", "", "",
    "Which of the following is not a function of a political party?",
    "A. Educating the government",
    "B. Interest articulation",
    "C. Aggregation of opinions",
    "D. Selection of persons for government",
    "C. Aggregation of opinions",
    "C"
    )),


        Questions( objective =Objective("30", "", "", "",
    "Franchise means the right of all qualified citizens to",
    "A. manipulate election results",
    "B. conduct elections",
    "C. enforce electoral laws",
    "D. vote and be voted for",
    "D. vote and be voted for",
    "D",
    )),


        Questions( objective =Objective("31", "", "", "",
    "The geographical units into which a country is divided for the purpose of election are called",
    "A. states",
    "B. constituencies",
    "C. polling areas",
    "D. county councils",
    "B. constituencies",
    "B",
    )),

        Questions( objective =Objective("32", "", "", "",
    "One way to ensure a free and fair election is to",
    "A. operate a one-party system",
    "B. allow parties to campaign on election day",
    "C. guarantee the security of electoral officers and materials",
    "D. appoint a politician as the chairman of the electoral commission",
    "C. guarantee the security of electoral officers and materials",
    "C",
    )),

        Questions( objective =Objective("33", "", "", "",
    "An election which involves the use of an electoral college is",
    "A. run-off election",
    "B. a general election",
    "C. an open balloting",
    "D. an indirect election",
    "D. an indirect election",
    "D",
    )),


        Questions( objective =Objective("34", "", "", "",
    "Which of the following functions is performed by the electoral commission?",
    "A. Distribution of party membership cards",
    "B. Presenting parties manifestoes",
    "C. Delimiting the country into constituencies",
    "D. Conducting oath of office for elected president",
    "C. Delimiting the country into constituencies",
    "C",
    )),




        Questions( objective =Objective("35", "", "", "",
    "Which of the following statements distinguishes political parties from pressure groups?",
    "A. Political parties only lobby government to change certain policies",
    "B. Pressure groups select candidates for political of fices",
    "C. Political parties influence government policies",
    "D. Pressure groups influence government policies to member's interest",
    "D. Pressure groups influence government policies to member's interest",
    "D",
    )),


        Questions( objective =Objective("36", "", "", "",
    "Public opinion enables a government to",
    "A. influence the public",
    "B. Suppress its opponents",
    "C. cut down the coat of governing",
    "D. know the feeling of the masses",
    "D. know the feeling of the masses",
    "D",
    )),


        Questions( objective =Objective("37", "", "", "",
    "The anonymity in the civil service means that a civil servant",
    "A. is above the law of the land",
    "B. receives neither praise nor blame",
    "C. should take part in partisan politics",
    "D. should not be disciplined for any misconduct",
    "B. receives neither praise nor blame",
    "B",
    )),


        Questions( objective =Objective("38", "", "", "",
    "Which of the following is a problem of civil service?",
    "A. Red-tapism",
    "B. Offering professional advice to political leaders",
    "C. Continuous keeping of records",
    "D. Changing of government through election",
    "A. Red-tapism",
    "A",
    )),


        Questions( objective =Objective("39", "", "", "",
    "Public corporations are Set Up by",
    "A. a minister",
    "B. a director",
    "C. a permanent secretary",
    "D. an act of parliament",
    "D. an act of parliament",
    "D",
    )),


        Questions( objective =Objective("40", "", "", "",
    "Which of the following is true of a Public Corporation it is?",
    "A. established by a bye-law",
    "B. owned by the minister of finance",
    "C. set up to make profit for share holders",
    "D. set up to provide essential services",
    "D. set up to provide essential services",
    "D",
    )),


        Questions( objective =Objective("41", "", "", "",
    "All the following are problems facing local governments in the West Africa except",
    "A. shortage of trained personnel",
    "B. obtaining loans form banks",
    "C. nepotism",
    "D. corruption",
    "B. obtaining loans form banks",
    "B",
    )),


        Questions( objective =Objective("42", "", "", "",
    "Local authorities are established to",
    "A. bring government nearer to the people",
    "B. give more powers to the traditional rulers",
    "C. make people less loyal to the central government",
    "D. make central government interface in local affairs.",
    "A. bring government nearer to the people",
    "A",
    )),


        Questions( objective =Objective("43", "", "", "",
    "A British colony means",
    "A. a territory endowed with arable farm land",
    "B. an area for colonial plantation",
    "C. an area directly under the control of the traditional rulers and chiefs",
    "D. a territory acquired by the colonialists through settlement or conquest",
    "D. a territory acquired by the colonialists through settlement or conquest",
    "D",
    )),

        Questions( objective =Objective("44", "", "", "",
    "Which of the following was not a reason for the adoption of indirect Rule in British West African territories?",
    "A. The chiefs approved of it",
    "B. Administrative officers were in short supply",
    "C. there was insufficient funding",
    "D. the traditional rulers commanded respect among their subjects",
    "A. The chiefs approved of it",
    "A",
    )),


        Questions( objective =Objective("45", "", "", "",
    "A major disadvantage of the Indirect Rule System was that he",
    "A. economy was over industrialized",
    "B. appointments were based on qualification",
    "C. British failed to give qualitative education to Africans",
    "D. central administration was dominated by Africans",
    "C. British failed to give qualitative education to Africans",
    "C",
    )),



        Questions( objective =Objective("46", "", "", "",
    "The organ of the United Nations Organization that coordinates the activities of its specialized agencies the",
    "A. General Assembly",
    "B. International Court of Justice",
    "C. Economic and Social Council",
    "D. Trusteeship Council",
    "C. Economic and Social Council",
    "C",
    )),

        Questions( objective =Objective("47", "", "", "",
    "The primary objective of the United Nations Organization (UNO) is to",
    "A. stop aggression",
    "B. help poor countries",
    "C. fight against injustice",
    "D. maintain world peace",
    "D. maintain world peace",
    "D",
    )),


        Questions( objective =Objective("48", "", "", "",
    "Which of the following international organizations did all West African countries belong to?",
    "A. Organization of Petroleum Exporting Countries",
    "B. North Atlantic Treaty Organization",
    "C. European Union",
    "D. Organization of African Unity",
    "D. Organization of African Unity",
    "D",
    )),


        Questions( objective =Objective("49", "", "", "",
    "Which of the following is not an organ of the Organization of African Unity (OAU)? The",
    "A. Assembly of Heads of State and Government",
    "B. Tribunal of the Community",
    "C. Council of Ministers",
    "D. Secretariat",
    "B. Tribunal of the Community",
    "B",
    )),


        Questions( objective =Objective("50", "", "", "",
    "The headquarters of the Economic Community of West African States (ECOWAS) Fund for Cooperation Compensation and Development is located in",
    "A. Lome",
    "B. Lagos",
    "C. Accra",
    "D. Dakar",
    "A. Lome",
    "A",
    )),


    )
}