package com.example.repository.government

import com.example.repository.Objective
import com.example.repository.Questions

class Government2015Repo {
    val government2015 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "which of the following best defines government as an institution of a state?",
            "A. An institution established for class struggle",
            "B. Machinery established for exercising political power",
            "C. A process of organizing societal values",
            "D. The art through which political parties are managed",
            "B. Machinery established for exercising political power", "B", )
        ),

        Questions( objective = Objective( "2", "", "", "",
            "Which of the following is a reason for studying government?",
            "A. knowledge of the rights of the individuals",
            "B. Acquisition of skills to work in a state owned industry",
            "C. Helps the individual to form a pressure group",
            "D. Enables citizens to vote during elections",
            "A. knowledge of the rights of the individuals", "A",)),


        Questions( objective = Objective( "3", "", "", "",
            "The most visible feature of a state is",
            "A. compulsory membership",
            "B. defined geographical territory",
            "C. written constitution",
            "D. sovereign power",
            "D. sovereign power",
            "D",
        )),

        Questions( objective = Objective( "4", "", "", "",
            "Representative democracy is characterized by",
            "A. free election and proper register of voters",
            "B. a politically educated elite",
            "C. representation of the poor only",
            "D. rule of the interest groups",
            "A. free election and proper register of voters",
            "A",
        )),

        Questions( objective = Objective( "5", "", "", "",
            "The set of attitudes and beliefs that determine the behaviour of citizens in a political system is called",
            "A. socialization",
            "B. political culture",
            "C. representative government",
            "D. devolution",
            "B. political culture",
            "B",
        )),

        Questions( objective = Objective( "6", "", "", "",
            "Fundamental Human Rights are entrenched in constitutions purposely to",
            "A. ensure freedom of speech",
            "B. guarantee the liberty of citizens",
            "C. promote good governance",
            "D. promote trade",
            "B. guarantee the liberty of citizens",
            "B",
        )),

        Questions( objective = Objective( "7", "", "", "",
            "Diplomatic and parliamentary immunities put limitations on",
            "A. the rule of law",
            "B. separation of powers",
            "C. checks and balances",
            "D. foreign policies",
            "A. the rule of law",
            "A",
        )),

        Questions( objective = Objective( "8", "", "", "",
            "Montesquieu's political theory of separation of powers was meant to",
            "A. promote unity in government",
            "B. prevent dictatorial rule",
            "C. ensure social justice",
            "D. enhance state security",
            "B. prevent dictatorial rule",
            "B",
        )),

        Questions( objective = Objective( "9", "", "", "",
            "Which of the following countries practices a centralized system of government?",
            "A. Nigeria",
            "B. Ghana",
            "C. USA",
            "D. India",
            "B. Ghana",
            "B",
        )),

        Questions( objective = Objective( "10", "", "", "",
            "Which of the following countries operates unwritten constitution?",
            "A. Britain",
            "B. USA",
            "C. Japan",
            "D. Canada",
            "A. Britain",
            "A",
        )),


        Questions( objective = Objective( "11", "", "", "",
            "A constitution that can be amended through ordinary law making process is said to be",
            "A. written",
            "B. unwritten",
            "C. rigid",
            "D. flexible",
            "D. flexible",
            "D",
        )),

        Questions( objective = Objective( "12", "", "", "",
            "Which of the following systems of government operates on the checks and balances?",
            "A. Theocracy",
            "B. Presidential",
            "C. Parliamentary",
            "D. Monarchical",
            "B. Presidential",
            "B",
        )),

        Questions( objective = Objective( "13", "", "", "",
            "Confederal systems of government means",
            "A. powerful centre and weak component units",
            "B. weak centre and powerful component units",
            "C. powerful centre and powerful component units",
            "D. weak component units and weak centre",
            "B. weak centre and powerful component units",
            "B",
        )),

        Questions( objective = Objective( "14", "", "", "",
            "In a federal system of government, the power shared between the Centre and state governments is known as",
            "A. legislative power",
            "B. exclusive power",
            "C. concurrent power",
            "D. judicial power",
            "C. concurrent power",
            "C",
        )),

        Questions( objective = Objective( "15", "", "", "",
            "The prerogative power resides with the",
            "A. ombudsman",
            "B. executive",
            "C. national assembly",
            "D. civil organization",
            "B. executive",
            "B",
        )),

        Questions( objective = Objective( "16", "", "", "",
            "Quick decision making is an advantage of",
            "A. unicameralism",
            "B. constitutionalism",
            "C. federalism",
            "D. republicanism",
            "A. unicameralism",
            "A",
        )),

        Questions( objective = Objective( "17", "", "", "",
            "The organ of government responsible for implementation of polices in a state is the",
            "A. legislature",
            "B. judiciary",
            "C. executive",
            "D. public bureau",
            "C. executive",
            "C",
        )),

        Questions( objective = Objective( "18", "", "", "",
            "A citizen is an individual who",
            "A. has the legal and political rights in a country",
            "B. has lived in a country for sometime",
            "C. enjoys only economic rights",
            "D. enjoys immunity in the country",
            "A. has the legal and political rights in a country",
            "A",
        )),


        Questions( objective = Objective( "19", "", "", "",
            "Which of the following is a condition for granting citizenship to a foreigner?",
            "A. Swearing an oath of allegiance",
            "B. Possession of a university degree",
            "C. A registered member of a political party",
            "D. Possession of an international passport",
            "A. Swearing an oath of allegiance",
            "A",
        )),

        Questions( objective = Objective( "20", "", "", "",
            "Citizenship can be acquired through all of the following methods except",
            "A. birth",
            "B. nationalization",
            "C. naturalization",
            "D. marriage",
            "B. nationalization",
            "B",
        )),

        Questions( objective = Objective( "21", "", "", "",
            "The conferment of citizenship on a distinguished personality of another country is called",
            "A. citizenship by birth",
            "B. honorary citizenship",
            "C. adoption",
            "D. citizenship by registration",
            "B. honorary citizenship",
            "B",
        )),

        Questions( objective = Objective( "22", "", "", "",
            "The primary aim of any political party is to",
            "A. pressurize the government",
            "B. remain in the opposition",
            "C. control the government",
            "D. ensure fair play in business",
            "C. control the government",
            "C",
        )),

        Questions( objective = Objective( "23", "", "", "",
            "A manifesto can be defined as the",
            "A. opportunity to form a political party",
            "B. proposed programmes of a political party",
            "C. policy of a political party in power",
            "D. power to rule the masses",
            "B. proposed programmes of a political party",
            "B",
        )),


        Questions( objective = Objective( "24", "", "", "",
            "Which of the following exists in a one - party state?",
            "A. Only the workers party is allowed to exist",
            "B. Only the students' party is allowed to exist",
            "C. Elections to the legislature are held at the party's conference",
            "D. The ruling party is the only legal party",
            "D. The ruling party is the only legal party",
            "D",
        )),

        Questions( objective = Objective( "25", "", "", "",
            "Which of the following party systems best represents all shades of opinions?",
            "A. Multi-party",
            "B. Two -party",
            "C. One- party",
            "D. Elite- party",
            "A. Multi-party",
            "A",
        )),


        Questions( objective = Objective( "26", "", "", "",
            "The practice of multi - party system in West Africa tends to promote",
            "A. sectionalism and factionalism",
            "B. national integration",
            "C. social discrimination",
            "D. economic integration",
            "B. national integration",
            "B",
        )),


        Questions( objective = Objective( "27", "", "", "",
            "Franchise is the right to",
            "A. express political views",
            "B. control the government",
            "C. vote and be voted for",
            "D. ensure good governance",
            "C. vote and be voted for",
            "C",
            )),

                    Questions( objective = Objective( "28", "", "", "",
                "The following are the aims of an election except that",
                "A. a group sticks on to power",
                "B. there is accountability of the leaders",
                "C. there is a smooth change of government",
                "D. the people determine who rules",
                "A. a group sticks on to power",
                "A",
            )),


            Questions( objective = Objective( "29", "", "", "",
                "Politics is practically demonstrated during",
                "A. electioneering campaigns",
                "B. parliamentary debates",
                "C. formation of political parties",
                "D. inter-party consultative meetings",
                "A. electioneering campaigns",
                "A",
            )),

            Questions( objective = Objective( "30", "", "", "",
                "An election held to fill a vacant post in the legislature due to the death or resignation of a member is called",
                "A. run - off election",
                "B. electoral college",
                "C. bye - election",
                "D. primary elections",
                "C. bye - election",
                "C",
            )),


            Questions( objective = Objective( "31", "", "", "",
                "Which of the following is a function of pressure groups?",
                "A. Represent and protect the rich",
                "B. Protect the interest of government",
                "C. Serve as avenue for political victimization",
                "D. Provide forum for the ventilation of grievances",
                "D. Provide forum for the ventilation of grievances",
                "D",
            )),

            Questions( objective = Objective( "32", "", "", "",
                "Public opinion is defined as the",
                "A. aggregate views of the people",
                "B. sentiments of opposition parties",
                "C. consensus of the mass media",
                "D. reaction of pressure groups",
                "A. aggregate views of the people",
                "A",
            )),

            Questions( objective = Objective( "33", "", "", "",
                "Public opinion on the performance of a government is best measured by",
                        "A. military strength",
                        "B. general elections",
                        "C. the mass media",
                        "D. parliamentary debates",
                        "C. the mass media",
                "C",
            )),


            Questions( objective = Objective( "34", "", "", "",
                "The method in which a group of people are interviewed on a specific political issue is called",
                "A. referendum",
                "B. individual speech",
                "C. individual writing",
                "D. opinion sampling",
                "D. opinion sampling",
                "D",
            )),

            Questions( objective = Objective( "35", "", "", "",
                "The Civil Service is an administrative institution of",
                "A. the executive arm of government",
                "B. Public corporations",
                "C. Para - military organization",
                "D. a business enterprise",
                "A. the executive arm of government",
                "A",
            )),

            Questions( objective = Objective( "36", "", "", "",
                "Which of the following is a feature of the civil service?",
                "A. Disloloyalty",
                "B. Impartiality",
                "C. Political activism",
                "D. Temporary tenure",
                "B. Impartiality",
                "B",
            )),

            Questions( objective = Objective( "37", "", "", "",
                "The major source of local government revenue is",
                "A. donations",
                "B. income from investments",
                "C. loans from finance institutions",
                "D. grants from the central authority",
                "D. grants from the central authority",
                "D",
            )),

            Questions( objective = Objective( "38", "", "", "",
                "In the pre -colonial African political system, the functions of the kingmakers were performed by",
                "A. Age grades",
                "B. Woman",
                "C. Council of elders",
                "D. Special people",
                "A. Age grades",
                "A",
            )),


            Questions( objective = Objective( "39", "", "", "",
                "Colonialism is defined as the",
                "A. struggle against foreign domination",
                "B. political struggle for independence",
                "C. economic dependence on developed nations",
                "D. imposition of foreign rule on a territory",
                "D. imposition of foreign rule on a territory",
                "D",
            )),

            Questions( objective = Objective( "40", "", "", "",
                "Casting vote' was one of the ways the Governor in British West Africa controlled the",
                "A. Colonial treasurer",
                "B. Colonial secretary",
                "C. Native authority",
                "D. Legislative council",
                "D. Legislative council",
                "D",
            )),

            Questions( objective = Objective( "41", "", "", "",
                "The French policy of assimilation was based on the assumption that African culture was",
                "A. expensive",
                "B. inferior",
                "C. unpopular",
                "D. superior",
                "B. inferior",
                "B",
            )),


            Questions( objective = Objective( "42", "", "", "",
                "The administrative structure  adopted in the French colonial territories was",
                "A. more of a centralized administration",
                "B. focused mainly on traditional rulers",
                "C. favourable to the African age grades",
                "D. for the development of African culture",
                "A. more of a centralized administration",
                "A",
            )),

            Questions( objective = Objective( "43", "", "", "",
                "The Pan -African Movements emerged as a result of",
                "A. African cultural heritage",
                "B. European racial domination",
                "C. the formation of the African Union",
                "D. the growth of socialism in Europe",
                "B. European racial domination",
                "B",
            )),

            Questions( objective = Objective( "44", "", "", "",
                "Which of the following was the first print media used by nationalists to oppose colonialism in the British West Africa?",
                "A. Daily News",
                "B. Daily Times",
                "C. West African pilot",
                "D. Guardian newspaper",
                "C. West African pilot",
                "C",
            )),

            Questions( objective = Objective( "45", "", "", "",
                "One of the prominent West African nationalist leaders was",
                "A. Kwane Nkrumah",
                "B. Jomo Kenyatta",
                "C. S. L. Akintola",
                "D. Sekou Tource",
                "A. Kwane Nkrumah",
                "A",
            )),

            Questions( objective = Objective( "46", "", "", "",
                "Which of the following cannot be altered by a military coup d'etat? The",
                "A. constitution",
                "B. legal system",
                "C. legislature",
                "D. state",
                "A. constitution",
                "A",
            )),

            Questions( objective = Objective( "47", "", "", "",
                "Laws promulgated by a military government are called",
                "A. bills",
                "B. acts",
                "C. decress",
                "D. proclamations",
                "C. decress",
                "C",
            )),

            Questions( objective = Objective( "48", "", "", "",
                "The origin of the Commonwealth of Nations can be traced to",
                "A. colonial ties",
                "B. world economic order",
                "C. equality of states",
                "D. sovereignty of states",
                "A. colonial ties",
                "A",
            )),


            Questions( objective = Objective( "49", "", "", "",
                "The first black African to hold the position of UN Secretary-General was",
                "A. Salim Ahmed Salirn",
                "B. Kofi Annan",
                "C. Emeka Anyaoku",
                "D. Nelson Mandela",
                "B. Kofi Annan",
                "B",
            )),


            Questions( objective = Objective( "50", "", "", "",
                "The Secretary-General of the United Nations Organization (UNO) is appointed for a period of",
                "A. there years",
                "B. five years",
                "C. Seven years",
                "D. nine years",
                "B. five years",
                "B",
            )),

            )
}