package com.example.repository.government

import com.example.repository.Objective
import com.example.repository.Questions

class Government2020Repo {
    val government2020 = listOf<Questions>(
        Questions( objective = Objective( "1", "", "", "",
            "In modern democracy, a government is _________",
            "A. a contrast between the rulers and the ruled",
            "B. a preserve of the political party in power",
            "C. monopoly of the ethnic group",
            "D. alternation of power between the majority and minority tribes",
            "A. a contrast between the rulers and the ruled", "A", )),


        Questions( objective = Objective( "2", "", "", "",
            "The ability to make and enforce laws and administer justice constitute the major functions of a _________",
            "A. nation",
            "B. society",
            "C. government",
            "D. pressure group",
            "C. government",
            "C",
        )),

        Questions( objective = Objective( "3", "", "", "",
            "Execute power in a cabinet system of government is vested in the ________",
            "A. legislature",
            "B. judiciary",
            "C. civil service",
            "D. council of ministers",
            "D. council of ministers",
            "D",
        )),


        Questions( objective = Objective( "4", "", "", "",
            "A feature of a confederal state is that _______",
            "A. it is a single sovereign state",
            "B. its constitution is flexible",
            "C. any unit can secede at will",
            "D. its powers are distributed equally between the centre and units",
            "C. any unit can secede at will",
            "C",
        )),


        Questions( objective = Objective( "5", "", "", "",
            "One of the limitations to the principles of rule of law is _________",
            "A. Immunity",
            "B. equality",
            "C. liberty",
            "D. impartiality",
            "A. Immunity",
            "A"
        )),

        Questions( objective = Objective( "6", "", "", "",
            "Countries adopt unitary system of government because it __________",
            "A. detests dictatorship",
            "B. promote national integration",
            "C. concentrates power only at the centre",
            "D. allows the component units to secede at will",
            "B. promote national integration",
            "B",
        )),


        Questions( objective = Objective( "7", "", "", "",
            "Which of the following is an advantage of monocephalous executive ___________",
            "A. sharing of power",
            "B. quick decision making",
            "C. impartial dispension of justice",
            "D. enjoyment of press freedom",
            "B. quick decision making",
            "B",
        )),

        Questions( objective = Objective( "8", "", "", "",
            "A major difference between power and authority is that, authority is ________",
            "A. scarcely exercised",
            "B. more dependent on coercion",
            "C. acquired popularly",
            "D. exercised through force",
            "C. acquired popularly",
            "C",
        )),

        Questions( objective = Objective( "9", "", "", "",
            "Political participation can take the form of __________",
            "A. belonging to a trade union",
            "B. being a member of a pressure group",
            "C. canvassing for votes",
            "D. organizing festival for good harvest",
            "C. canvassing for votes",
            "C",
        )
        ),

        Questions( objective = Objective( "10", "", "", "",
            "Which of the following is a disadvantage of proportional representation?",
            "A. encourages rigging",
            "B. promotes strong government",
            "C. makes for easy decision making in parliament",
            "D. is difficult and cumbersome to operate",
            "D. is difficult and cumbersome to operate",
            "D",
        )),


        Questions( objective = Objective( "11", "", "", "",
            "The sum total of authority in a state unrestrained by law is _______",
            "A. monarchy",
            "B. society",
            "C. oligarchy",
            "D. sovereignty",
            "D. sovereignty",
            "D",
        )),


        Questions( objective = Objective( "12", "", "", "",
            "The flexibility and rigidity of constitution refer to the __________",
            "A. sources of constitution",
            "B. making of constitution",
            "C. ease of amending constitution",
            "D. coding of constitution",
            "C. ease of amending constitution",
            "C",
        )),

        Questions( objective = Objective( "13", "", "", "",
            "The observance of Rule of Law in a state requires _________",
            "A. an independent judiciary",
            "B. an ineffective police system",
            "C. a flexible constitution",
            "D. existence of a two-party system",
            "A. an independent judiciary",
            "A"
        )),


        Questions( objective = Objective( "14", "", "", "",
            "The principle of separating the judiciary from the other organs of government and making it free from executive and legislative influence is termed __________",
            "A. judicial independence",
            "B. judicial review",
            "C. separation of powers",
            "D. fusions of powers",
            "A. judicial independence",
            "A"
        )),


        Questions( objective = Objective( "15", "", "", "",
            "The right to respect the personality of the individual is a _________",
            "A. civil right",
                    "B. natural right",
            "C. social right",
            "D. economic right",
            "D. economic right",
            "D",
        )),

        Questions( objective = Objective( "16", "", "", "",
            "Which of the following constitutional provisions gives a high degree of autonomy to component parts of a unitary state?",
            "A. Devolution",
            "B. Delegation",
            "C. Divestiture",
            "D. Declaration",
            "A. Devolution",
            "A",
        )),

        Questions( objective = Objective( "17", "", "", "",
            "The following are redresses available at the courts for aggrieved people except _________",
            "A. injunction",
            "B. mandamus",
            "C. certiorari",
            "D. prorogation",
            "D. prorogation",
            "D",
        )),

        Questions( objective = Objective( "18", "", "", "",
            "Which of the following usually leads to the curtailment of the rights of citizens?",
            "A. transitional period",
            "B. granting of presidential pardon",
            "C. period pf constitutional pardon",
            "D. violent socio-political unrest",
            "D. violent socio-political unrest",
            "D",
        )),


        Questions( objective = Objective( "19", "", "", "",
            "The national secretariat of a political party is managed by the ________",
            "A. presidential candidate",
            "B. funding members",
            "C. national chairman and general secretary",
            "D. national executive and youth organizer",
            "C. national chairman and general secretary",
            "C",
        )),


        Questions( objective = Objective( "20", "", "", "",
            "The type of election which allows party members to elect candidates for elective offices is _________",
            "A. general election",
            "B. bye election",
            "C. direct election",
            "D. primary election",
            "D. primary election",
            "D",
        )),


        Questions( objective = Objective( "21", "", "", "",
            "An opposition party which sees itself as ''government -in-waiting'' is called ___________",
            "A. shadow government",
            "B. caretaker government",
            "C. national government",
            "D. responsible government",
            "A. shadow government",
            "A",
        )),


        Questions( objective = Objective( "22", "", "", "",
            "The document which sets out the programme of a political party and guides the electorate to vote for it is the ________",
            "A. constitution",
            "B. electoral register",
            "C. manifesto",
            "D. white paper",
            "C. manifesto",
            "C",
        )),

        Questions( objective = Objective( "23", "", "", "",
            "An advantage of a two-party system is that it __________",
            "A. simplifies the electoral process",
            "B. ensures winner takes all",
            "C. protects the electoral commission",
            "D. protects the electorate from vote buying",
            "A. simplifies the electoral process",
            "A",
        )),


        Questions( objective = Objective( "24", "", "", "",
            "Which of the following is a non-partisan organization with the aim of influencing government policies?",
            "A. Political party",
            "B. Pressure group",
            "C. Humanitarian",
            "D. Relief organization",
            "B. Pressure group",
            "B",
        )),


        Questions( objective = Objective( "25", "", "", "",
            "The collective views held by majority of citizens of a country about a particular policy is _________",
                    "A. national interest",
            "B. public opinion",
            "C. commentary",
            "D. bulletin",
            "B. public opinion",
            "B",
        )),


        Questions( objective = Objective( "26", "", "", "",
            "An institution under the executive arm of government responsible for formulating and implementing government policies is the ________",
            "A. public service",
            "B. public corporation",
            "C. civil service",
            "D. judicial service",
            "C. civil service",
            "C",
        )),


        Questions( objective = Objective( "27", "", "", "",
            "The following are means of controlling public corporation except _________",
            "A. legislative control",
            "B. judicial control",
            "C. ministerial control",
            "D. chief of staff control",
            "D. chief of staff control",
            "D",
        )),

        Questions( objective = Objective( "28", "", "", "",
            "The institution established by the constitution to be responsible for recruiting personnel into the civil service is the ___________",
            "A. personnel management office",
            "B. office of the president",
            "C. National labour commission",
            "D. Public service commission",
            "D. Public service commission",
            "D",
        )),


        Questions( objective = Objective( "29", "", "", "",
            "If a winner emerges in an election as a result of his/her votes being more than the combined votes of the opposing contestants; what types of electoral system is being practised?",
            "A. Absolute majority",
            "B. plurality",
            "C. second ballot",
            "D. alternative vote",
            "A. Absolute majority",
            "A",
        )),


        Questions( objective = Objective( "30", "", "", "",
            "Which of the following is a function of an electoral commission?",
            "A. adjudicating election petitions",
            "B. provision of electoral registers",
            "C. disciplining personnel in the civil service",
            "D. promotion of public servants",
            "B. provision of electoral registers",
            "B",
        )),

        Questions( objective = Objective( "31", "", "", "",
            "Which of the following is not an electoral malpratice?",
            "A. impersonation",
            "B. threatening",
            "C. campaigning for a candidate",
            "D. gerrymandering",
            "C. campaigning for a candidate",
            "C",
        )),


        Questions( objective = Objective( "32", "", "", "",
            "Local government sources of revenue can best be improved through?",
            "A. schools",
            "B. the collection of import duties",
            "C. the provision of housing units",
            "D. cottage industries",
            "D. cottage industries",
            "D"
        )),


        Questions( objective = Objective( "33", "", "", "",
            "Public opinion is important in that, it ________",
            "A. helps political parties to assess their policies",
            "B. creates delays in the execution of policies",
            "C. may be unreliable and misleading",
            "D. can be manipulated by political opponents",
            "A. helps political parties to assess their policies",
            "A",
        )),


        Questions( objective = Objective( "34", "", "", "",
            "One of the features of pressure groups is that all members ________",
            "A. are rich",
            "B. think in the same way",
            "C. have similar interests",
            "D. oppose the government",
            "C. have similar interests",
            "C"
        )),


        Questions( objective = Objective( "35", "", "", "",
            "Which of the following modes of operation of pressure group undermines economics, social and political stability of the state ________",
            "A. Lobbying",
            "B. symposia",
            "C. strikes",
            "D. debates",
            "C. strikes",
            "C",
        )),


        Questions( objective = Objective( "36", "", "", "",
            "The police reform all the following functions except ________",
            "A. Public execution of law breakers",
            "B. prosecuting law breakers",
            "C. protection of life and property",
            "D. enforcement of law and order",
            "A. Public execution of law breakers",
            "A",
        )),


        Questions( objective = Objective( "34", "", "", "",
            "Which of the following is a reason for the failure of the assimilation policy in French West Africa?",
            "A. The change in name of their culture",
            "B. The refusal of the African to be culturally colonized",
            "C. The paternal policy of the French",
            "D. Bribery of the opinion leaders by the French",
            "B. The refusal of the African to be culturally colonized",
            "B"
        )),

        Questions( objective = Objective( "38", "", "", "",
            "The capital of the French Federation of West Africa states was located in?",
            "A. Bamako, Mali",
            "B. Dakar, Senegal",
            "C. Conakry. Guinea",
            "D. Niamey,Niger",
            " B. Dakar, Senegal",
            "B"
        )),


        Questions( objective = Objective( "39", "", "", "",
            "Under the crown colony system of administration, major policies were implemented in the colonies by the ________",
            "A. Chiefs and their elders",
            "B. Secretary of states for the colonies",
            "C. Chiefs and the British",
            "D. Colonial governor",
            "B. Secretary of states for the colonies",
            "B",
        )),



        Questions( objective = Objective( "40", "", "", "",
            "One way of improving productivity in the public service is through?",
            "A. promotion without examination",
            "B. higher salaries and allowances",
            "C. increase in working hours",
            "D. open door policy",
            "D. open door policy",
            "D",
        )),

        Questions( objective = Objective( "41", "", "", "",
            "Which of the following made the colonial Government a Virtual Dictator?",
            "A. Legislative council",
            "B. Executive council",
            "C. appointment of departmental heads",
            "D. Reserved veto powers",
            "D. Reserved veto powers",
            "D"
        )),


        Questions( objective = Objective( "42", "", "", "",
            "Which of the following is a feature of the French policy of Association?",
            "A. Elevation of the position of the chiefs",
            "B. French citizenship to subjects",
            "C. scholarships to needy students",
            "D. language barrier and race",
            "B. French citizenship to subjects",
            "B"
        )),

        Questions( objective = Objective( "43", "", "", "",
            "The African Union is most often unable to resolve conflicts because of _________",
            "A. financial weekness",
            "B. absence of African High Command",
            "C. Differences in Culture",
            "D. Language barrier and race",
            "B. absence of African High Command",
            "B",
        )),


        Questions( objective = Objective( "44", "", "", "",
            "The formation of the African Union is aimed at achieving a wider goal of ________",
            "A. cultural integration",
            "B. continental government",
            "C. national solidarity",
            "D. African identity",
            "A. cultural integration",
            "A",
        )),


        Questions( objective = Objective( "45", "", "", "",
            "A major advantage of a country's foreign policy is that, it __________",
            "A. encourages infringement on the territories of other states",
            "B. promotes the country's national interest",
            "C. stimulates political activities in the state",
            "D. promotes understanding between the leaders and the led",
            "B. promotes the country's national interest",
            "B",
        )),


        Questions( objective = Objective( "46", "", "", "",
            "The West African Students Union (WASU) was formed by _______",
            "A. Siaka Stevens",
            "B. K. A. Gbedemah",
            "C. E.F Small",
            "D. OLadipo Solake",
            " D. OLadipo Solake",
            "D",
        )),


        Questions( objective = Objective( "47", "", "", "",
            "A military coup d'etat is followed by _________",
            "A. enforcement of fundamental human rights",
            "B. suspension of the constitution",
            "C. breaking of diplomatic relations with foreign countries",
            "D. mass importation of firearms",
            "B. suspension of the constitution",
            "B",
        )),


        Questions( objective = Objective( "48", "", "", "",
            "Which of the following countries is a Unitary?",
            "A. Nigeria",
            "B. Egypt",
            "C. Ghana",
            "D. Canada",
            "C. Ghana",
            "C",
        )),


        Questions( objective = Objective( "49", "", "", "",
            "Which of the following does not influence a country's foreign policy?",
            "A. Desire for foreign investments",
            "B. International law, Conventions and Treaties",
            "C. Religion and racial factors",
            "D. Age of the leader",
            "D. Age of the leader",
            "D",
        )),


        Questions( objective = Objective( "50", "", "", "",
            "The National Congress of British West Africa (NCBWA) was founded in",
            "A. Sierra Leone",
            "B. Liberia",
            "C. Ghana",
            "D. Nigeria",
            "C. Ghana",
            "C",
        )),

        )
}